'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { CheckCircle2, Hash, Loader2, LockKeyhole, ShieldCheck, XCircle } from 'lucide-react';
import AppLogo from '@/components/ui/AppLogo';

export default function ValidateCaseFilePage() {
  const { id } = useParams<{ id: string }>();
  const [result, setResult] = useState<any>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/validate-case-file`, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '' }, body: JSON.stringify({ case_file_id: id }) }).then((response) => response.json()).then(setResult).catch(() => setResult({ valid: false, error: 'No fue posible conectar con el servicio de verificación.' })).finally(() => setLoading(false)); }, [id]);
  return <div className="min-h-screen bg-[#F8F8FB] px-4 py-10 text-[#18181B]"><div className="mx-auto max-w-2xl"><AppLogo className="[&_img]:h-auto [&_img]:w-[126px]" /><div className="mt-8 rounded-md border border-[#EBEBF0] bg-white p-6 md:p-8">{loading ? <div className="flex min-h-72 items-center justify-center"><Loader2 size={28} className="animate-spin text-[#4F46E5]" /></div> : result?.valid ? <><span className="flex h-14 w-14 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2 size={26} /></span><p className="mt-5 text-xs font-semibold uppercase text-emerald-600">Integridad verificada</p><h1 className="mt-1 text-2xl font-semibold">Expediente cerrado herméticamente</h1><p className="mt-2 text-sm text-[#52525B]">La constancia y el hash raíz corresponden al expediente sellado por Docubox.</p><div className="mt-6 divide-y divide-[#EBEBF0] rounded-md border border-[#EBEBF0] px-4"><Data label="Constancia" value={result.certificate_number} /><Data label="Folio" value={result.case_file?.folio} /><Data label="Expediente" value={result.case_file?.title} /><Data label="Fecha de cierre" value={new Date(result.closed_at).toLocaleString('es-MX')} /><Data label="Algoritmo" value={result.hash_algorithm} /></div><div className="mt-5 rounded-md bg-[#F8F8FB] p-4"><p className="flex items-center gap-2 text-xs font-semibold"><Hash size={14} />Hash raíz</p><p className="mt-2 break-all font-mono text-xs leading-5 text-[#52525B]">{result.root_hash}</p></div><div className="mt-6 flex items-start gap-3 text-xs leading-5 text-[#71717A]"><LockKeyhole size={16} className="mt-0.5 shrink-0 text-[#4F46E5]" />El expediente permanece bloqueado para modificación ordinaria. Una reapertura excepcional genera nueva evidencia y no altera este cierre.</div></> : <div className="py-12 text-center"><XCircle size={40} className="mx-auto text-red-500" /><h1 className="mt-4 text-xl font-semibold">No se pudo verificar</h1><p className="mt-2 text-sm text-[#71717A]">{result?.error || 'La constancia no está disponible.'}</p></div>}</div><p className="mt-5 flex items-center justify-center gap-2 text-xs text-[#71717A]"><ShieldCheck size={14} />Servicio público de verificación Docubox</p></div></div>;
}
function Data({ label, value }: { label: string; value?: string }) { return <div className="flex flex-col gap-1 py-3 sm:flex-row sm:justify-between"><span className="text-xs text-[#71717A]">{label}</span><span className="text-sm font-medium">{value || '—'}</span></div>; }
