'use client';

import { Check, Copy, FileText, MoreHorizontal, Plus } from 'lucide-react';
import AppLayout from '@/components/AppLayout';
import { CASE_TEMPLATES } from '@/lib/case-files/schema';
import { CaseWorkspace, SectionHeader } from '../components/CaseUI';

export default function PlantillasExpedientePage() {
  return <AppLayout noPadding><CaseWorkspace><SectionHeader title="Plantillas de expediente" description="Define requisitos, identidad, hitos y condiciones de cierre reutilizables por tipo de expediente." action={<button className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3.5 text-sm font-600 text-primary-foreground"><Plus size={15} /> Nueva plantilla</button>} /><div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{CASE_TEMPLATES.map((template) => <article key={template.id} className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm shadow-slate-200/30 dark:border-border dark:bg-card"><header className="flex items-start justify-between border-b border-slate-200 p-4 dark:border-border"><span className="flex h-10 w-10 items-center justify-center rounded-md border border-blue-100 bg-blue-50 text-primary"><FileText size={18} /></span><button aria-label="Más acciones" className="flex h-8 w-8 items-center justify-center rounded-md text-slate-500 hover:bg-slate-50"><MoreHorizontal size={17} /></button></header><div className="p-4"><p className="text-xs font-semibold text-primary">{template.type}</p><h2 className="mt-1 text-base font-semibold text-slate-950 dark:text-foreground">{template.name}</h2><p className="mt-2 min-h-10 text-sm leading-5 text-slate-500">{template.description}</p><div className="mt-4 grid grid-cols-3 overflow-hidden rounded-md border border-slate-200"> <Metric value={template.requirements.length} label="requisitos" /><Metric value={template.identityMethods.length} label="validaciones" /><Metric value={template.milestones.length} label="hitos" /></div><div className="mt-4 space-y-2">{template.requirements.slice(0, 4).map((item) => <div key={item.name} className="flex items-center gap-2 text-xs text-slate-600"><Check size={12} className="text-emerald-600" />{item.name}</div>)}</div></div><footer className="flex gap-2 border-t border-slate-200 p-3 dark:border-border"><button className="h-9 flex-1 rounded-md border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50 dark:border-border">Editar</button><button className="flex h-9 w-9 items-center justify-center rounded-md border border-slate-200 text-slate-600 hover:bg-slate-50 dark:border-border" title="Duplicar"><Copy size={14} /></button></footer></article>)}</div></CaseWorkspace></AppLayout>;
}

function Metric({ value, label }: { value: number; label: string }) {
  return <div className="border-r border-slate-200 bg-slate-50 p-2 text-center last:border-r-0 dark:bg-background"><p className="text-sm font-semibold">{value}</p><p className="text-[10px] text-slate-500">{label}</p></div>;
}
