'use client';
import { useEffect, useState } from 'react';
import AppLayout from '@/components/AppLayout';
import { CertificationHeader, CertificationWorkspace, SandboxNotice } from '@/components/certifica/CertificationUI';
import { useWorkspace } from '@/contexts/WorkspaceContext';
import { useCertificaApi } from '@/lib/certifica/client';
export default function Page() { const { activeWorkspace } = useWorkspace(); const api = useCertificaApi(); const [data, setData] = useState<any>(null); useEffect(() => { if (activeWorkspace?.id) api(`/api/certifica/configuration?workspace_id=${activeWorkspace.id}`).then(setData).catch(() => setData({ runtime: { mode: 'sandbox', healthy: false, detail: 'No se pudo consultar el proveedor.' }, providers: [] })); }, [activeWorkspace?.id, api]); return <AppLayout noPadding><CertificationWorkspace><CertificationHeader title="Configuracion" description="Estado sanitario de productos y proveedores de certificacion." /><div className="space-y-4"><SandboxNotice /><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">Proveedor en tiempo de ejecucion</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><Field label="Entorno" value={data?.runtime?.mode || 'Consultando'} /><Field label="Estado" value={data?.runtime?.healthy ? 'Operativo' : 'No configurado'} /><Field label="Detalle" value={data?.runtime?.detail || 'Consultando'} /></div></section><section className="rounded-lg border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold">Regla de produccion</h2><p className="mt-2 text-sm leading-6 text-slate-500">El sistema no muestra una constancia PSC valida si faltan endpoint, credencial de backend o validacion de respuesta. Un fallo deja la operacion cerrada y auditable.</p></section></div></CertificationWorkspace></AppLayout>; }
function Field({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold uppercase text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }

