'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  AlertTriangle, ArrowLeft, Check, CheckCircle2, ChevronLeft, ChevronRight, ClipboardCheck,
  FileCheck2, Fingerprint, Gauge, Loader2, LockKeyhole, PlayCircle, Plus,
  Save, ShieldCheck, Trash2, UsersRound, Video,
} from 'lucide-react';
import AppLayout from '@/components/AppLayout';
import { useWorkspace } from '@/contexts/WorkspaceContext';
import { useAuth } from '@/contexts/AuthContext';
import { createClient } from '@/lib/supabase/client';
import { getIdentityPolicy, saveIdentityPolicy } from '@/lib/identity/storage';
import {
  BASE_IDENTITY_POLICY, IDENTITY_POLICY_PRESETS, clonePolicyConfig, policyControlCount,
  policyFriction, type IdentityDocumentRequirement, type IdentityPolicyConfig,
} from '@/lib/identity/schema';

const steps = [
  { title: 'Aplicacion', icon: ClipboardCheck, description: 'Alcance, participantes y momento de verificacion.' },
  { title: 'Enrolamiento', icon: UsersRound, description: 'Reutilizacion y revalidacion de identidades previas.' },
  { title: 'Identidad', icon: Fingerprint, description: 'Captura facial, prueba de vida y controles complementarios.' },
  { title: 'Documentos', icon: FileCheck2, description: 'Requisitos KYC o KYB configurables.' },
  { title: 'Consentimiento', icon: Video, description: 'Privacidad, biometria y manifestacion de voluntad.' },
  { title: 'Resultado', icon: Gauge, description: 'Decisiones, evidencia, reintentos y umbrales.' },
];

const inputClass = 'h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10 dark:border-border dark:bg-background dark:text-foreground';

export default function IdentityPolicyBuilder({ policyId }: { policyId?: string }) {
  const router = useRouter();
  const { activeWorkspace } = useWorkspace();
  const { user } = useAuth();
  const [step, setStep] = useState(0);
  const [config, setConfig] = useState<IdentityPolicyConfig>(() => clonePolicyConfig(BASE_IDENTITY_POLICY));
  const [currentId, setCurrentId] = useState(policyId);
  const [loading, setLoading] = useState(Boolean(policyId));
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [testOpen, setTestOpen] = useState(false);

  useEffect(() => {
    if (!policyId || !activeWorkspace?.id) return;
    getIdentityPolicy(createClient(), activeWorkspace.id, policyId).then((record) => {
      if (record) setConfig(clonePolicyConfig(record.config));
      else setMessage('No se encontro la politica. Puedes guardar una nueva version desde esta configuracion.');
      setLoading(false);
    });
  }, [policyId, activeWorkspace?.id]);

  const summary = useMemo(() => ({
    controls: policyControlCount(config),
    friction: policyFriction(config),
    documents: config.documents.length,
    blockers: [!config.name.trim() ? 'Agrega un nombre' : '', !config.privacyConsent ? 'Activa el aviso de privacidad' : '', !config.biometricConsent && config.livenessMode ? 'Activa el consentimiento biometrico' : ''].filter(Boolean),
  }), [config]);

  const persist = async (status: 'draft' | 'active') => {
    if (!activeWorkspace?.id || !user?.id) { setMessage('No se encontro el espacio de trabajo activo.'); return; }
    if (!config.name.trim()) { setStep(0); setMessage('Asigna un nombre a la politica antes de guardarla.'); return; }
    setSaving(true); setMessage('');
    const result = await saveIdentityPolicy(createClient(), activeWorkspace.id, user.id, config, { id: currentId, status });
    setCurrentId(result.record.id);
    setSaving(false);
    setMessage(status === 'active' ? `Version ${result.record.version} publicada y activada.` : 'Borrador guardado.');
    if (!policyId && result.record.id) window.history.replaceState(null, '', `/configuracion/verificacion-identidad/${result.record.id}`);
  };

  if (loading) return <AppLayout noPadding><div className="flex min-h-[calc(100vh-4rem)] items-center justify-center bg-[#f6f8fb]"><Loader2 size={24} className="animate-spin text-primary" /></div></AppLayout>;

  return <AppLayout noPadding>
    <div className="-mx-4 -my-4 min-h-[calc(100vh-4rem)] bg-[#f6f8fb] dark:bg-background md:-my-6">
      <header className="flex min-h-[72px] items-center justify-between border-b border-slate-200 bg-white px-4 dark:border-border dark:bg-card md:px-6">
        <div className="flex min-w-0 items-center gap-3"><button onClick={() => router.push('/configuracion/verificacion-identidad')} aria-label="Cerrar configurador" className="flex h-9 w-9 flex-none items-center justify-center rounded-md border border-slate-200 text-slate-600 hover:bg-slate-50"><ArrowLeft size={17} /></button><div className="min-w-0"><div className="flex items-center gap-2"><h1 className="truncate text-sm font-600">{config.name || 'Nueva politica de verificacion'}</h1><span className="rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-600 text-amber-700">Borrador</span></div><p className="mt-0.5 hidden text-xs text-slate-500 sm:block">Versiona las reglas que deberan completarse antes de firmar.</p></div></div>
        <div className="flex items-center gap-2"><button onClick={() => setTestOpen(true)} className="hidden h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-3 text-xs font-600 text-slate-700 hover:bg-slate-50 md:inline-flex"><PlayCircle size={14} /> Probar</button><button onClick={() => persist('draft')} disabled={saving} className="inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-3 text-xs font-600 text-slate-700 hover:bg-slate-50 disabled:opacity-60"><Save size={14} /> Guardar</button><button onClick={() => persist('active')} disabled={saving || summary.blockers.length > 0} className="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-xs font-600 text-white hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50">{saving ? <Loader2 size={14} className="animate-spin" /> : <ShieldCheck size={14} />} Publicar</button></div>
      </header>

      {message && <div className="border-b border-blue-200 bg-blue-50 px-4 py-2.5 text-center text-xs text-blue-700">{message}</div>}

      <div className="mx-auto grid max-w-[1680px] md:grid-cols-[228px_minmax(0,1fr)] xl:grid-cols-[228px_minmax(0,1fr)_286px]">
        <aside className="hidden min-h-[calc(100vh-72px)] border-r border-slate-200 bg-white p-3 dark:border-border dark:bg-card md:block">
          <p className="mb-2 px-3 pt-2 text-[10px] font-600 uppercase text-slate-400">Configuracion</p>
          <nav className="space-y-1">{steps.map((item, index) => { const Icon = item.icon; const active = step === index; return <button key={item.title} onClick={() => setStep(index)} className={`flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm transition ${active ? 'bg-blue-50 font-600 text-primary' : 'text-slate-600 hover:bg-slate-50 dark:text-muted-foreground'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-md ${active ? 'bg-white text-primary shadow-sm' : 'text-slate-400'}`}><Icon size={15} /></span><span className="flex-1">{index + 1}. {item.title}</span>{active && <ChevronRight size={14} />}</button>; })}</nav>
        </aside>

        <main className="min-w-0 px-4 py-6 md:px-7 lg:px-10">
          <div className="mx-auto max-w-4xl">
            <div className="mb-5"><div className="flex items-center gap-2 text-xs font-600 text-primary"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-blue-50">{step + 1}</span>Paso {step + 1} de {steps.length}</div><h2 className="mt-2 text-2xl font-600 text-slate-950 dark:text-foreground">{steps[step].title}</h2><p className="mt-1 text-sm text-slate-500">{steps[step].description}</p></div>
            <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/30 dark:border-border dark:bg-card md:p-6">
              {step === 0 && <ApplicationStep config={config} setConfig={setConfig} />}
              {step === 1 && <EnrollmentStep config={config} setConfig={setConfig} />}
              {step === 2 && <IdentityStep config={config} setConfig={setConfig} />}
              {step === 3 && <DocumentsStep config={config} setConfig={setConfig} />}
              {step === 4 && <ConsentStep config={config} setConfig={setConfig} />}
              {step === 5 && <ResultStep config={config} setConfig={setConfig} />}
            </section>
            <footer className="mt-5 flex items-center justify-between"><button onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0} className="inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-3 text-xs font-600 text-slate-600 disabled:opacity-0"><ChevronLeft size={14} /> Anterior</button>{step < steps.length - 1 ? <button onClick={() => setStep(step + 1)} className="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-4 text-xs font-600 text-white">Continuar <ChevronRight size={14} /></button> : <button onClick={() => persist('active')} disabled={summary.blockers.length > 0} className="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-4 text-xs font-600 text-white disabled:opacity-50"><ShieldCheck size={14} /> Publicar politica</button>}</footer>
          </div>
        </main>

        <aside className="hidden min-h-[calc(100vh-72px)] border-l border-slate-200 bg-white p-4 dark:border-border dark:bg-card xl:block">
          <div className="sticky top-24"><div className="flex items-center gap-2"><ShieldCheck size={16} className="text-primary" /><h2 className="text-sm font-600">Resumen</h2></div><p className="mt-1 text-xs leading-5 text-slate-500">Impacto estimado de esta politica.</p><div className="mt-4 overflow-hidden rounded-lg border border-slate-200"><Summary label="Nivel" value={labelAssurance(config.assuranceLevel)} /><Summary label="Controles" value={summary.controls} /><Summary label="Documentos" value={summary.documents} /><Summary label="Friccion" value={summary.friction} /></div><div className="mt-4 rounded-lg border border-blue-100 bg-blue-50 p-4"><p className="text-xs font-600 text-blue-800">Decisiones configuradas</p><div className="mt-3 space-y-2 text-xs text-blue-700"><p className="flex items-center gap-2"><Check size={12} /> Aprobacion desde {config.autoApproveScore}</p><p className="flex items-center gap-2"><AlertTriangle size={12} /> Revision desde {config.manualReviewScore}</p><p className="flex items-center gap-2"><LockKeyhole size={12} /> {config.blockOnFailure ? 'Firma bloqueada si falla' : 'Firma no bloqueada'}</p></div></div>{summary.blockers.length > 0 && <div className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-600 text-amber-800">Antes de publicar</p>{summary.blockers.map((item) => <p key={item} className="mt-2 text-xs text-amber-700">· {item}</p>)}</div>}</div>
        </aside>
      </div>

      {testOpen && <TestDialog config={config} onClose={() => setTestOpen(false)} />}
    </div>
  </AppLayout>;
}

function ApplicationStep({ config, setConfig }: StepProps) {
  return <div className="space-y-6"><div><SectionTitle title="Comenzar con una politica" description="Usa un preset y ajustalo al riesgo real del proceso." /><div className="grid gap-2 md:grid-cols-2">{IDENTITY_POLICY_PRESETS.map((preset) => <button key={preset.id} onClick={() => setConfig(clonePolicyConfig(preset.config))} className="rounded-md border border-slate-200 p-3 text-left transition hover:border-blue-300 hover:bg-blue-50/40"><p className="text-sm font-600">{preset.name}</p><p className="mt-1 text-xs leading-5 text-slate-500">{preset.description}</p></button>)}</div></div><Divider /><div className="grid gap-4 md:grid-cols-2"><Field label="Nombre de la politica" value={config.name} onChange={(name) => setConfig({ ...config, name })} placeholder="Firmante contractual reforzado" /><Select label="Tipo" value={config.type} onChange={(type) => setConfig({ ...config, type: type as IdentityPolicyConfig['type'] })} options={[['signature','Identidad para firma'],['kyc','KYC persona fisica'],['kyb','KYB persona moral'],['enrollment','Enrolamiento'],['revalidation','Revalidacion']]} /><Select label="Nivel de aseguramiento" value={config.assuranceLevel} onChange={(assuranceLevel) => setConfig({ ...config, assuranceLevel: assuranceLevel as IdentityPolicyConfig['assuranceLevel'] })} options={[['basic','Basico'],['standard','Estandar'],['enhanced','Reforzado'],['custom','Personalizado']]} /><Select label="Momento de verificacion" value={config.verificationMoment} onChange={(verificationMoment) => setConfig({ ...config, verificationMoment: verificationMoment as IdentityPolicyConfig['verificationMoment'] })} options={[['before_access','Antes de acceder'],['before_review','Antes de revisar'],['before_signing','Antes de firmar']]} /></div><div><Label>Descripcion</Label><textarea value={config.description} onChange={(event) => setConfig({ ...config, description: event.target.value })} rows={3} className={`${inputClass} h-auto py-2`} placeholder="Explica cuando debe utilizarse esta politica." /></div><CheckGroup title="Aplica a" options={['Documentos','Plantillas','Formularios','Expedientes']} selected={config.appliesTo} onChange={(appliesTo) => setConfig({ ...config, appliesTo })} /><CheckGroup title="Participantes" options={['Firmante','Aprobador','Testigo','Representante legal','Solicitante']} selected={config.participantTypes} onChange={(participantTypes) => setConfig({ ...config, participantTypes })} /><div className="grid gap-3 md:grid-cols-2"><Select label="Revision manual" value={config.manualReview} onChange={(manualReview) => setConfig({ ...config, manualReview: manualReview as IdentityPolicyConfig['manualReview'] })} options={[['never','Nunca'],['exception','Por excepcion'],['always','Siempre']]} /><Toggle label="Bloquear la firma si no se aprueba" description="El participante no podra continuar con el documento." checked={config.blockOnFailure} onChange={(blockOnFailure) => setConfig({ ...config, blockOnFailure })} /></div></div>;
}

function EnrollmentStep({ config, setConfig }: StepProps) { return <div className="space-y-6"><SectionTitle title="Reutilizacion de enrolamiento" description="El correo o telefono nunca se utilizan como identificador unico." /><Select label="¿Puede utilizarse un enrolamiento anterior?" value={config.reuseMode} onChange={(reuseMode) => setConfig({ ...config, reuseMode: reuseMode as IdentityPolicyConfig['reuseMode'] })} options={[['never','No, verificar completamente cada vez'],['valid','Si, mientras continue vigente'],['liveness','Si, con nueva prueba de vida'],['step_up','Si, con autenticacion reforzada'],['risk','Decidir automaticamente segun riesgo'],['approval','Solicitar autorizacion del administrador']]} /><div className="grid gap-4 md:grid-cols-2"><NumberField label="Antiguedad maxima" suffix="dias" value={config.maxEnrollmentAgeDays} onChange={(maxEnrollmentAgeDays) => setConfig({ ...config, maxEnrollmentAgeDays })} /><Select label="Vigencia de esta comprobacion" value={config.validityMode} onChange={(validityMode) => setConfig({ ...config, validityMode: validityMode as IdentityPolicyConfig['validityMode'] })} options={[['event','Por evento'],['document','Por documento'],['case_file','Por expediente'],['days','Por numero de dias']]} /></div><div className="grid gap-3 md:grid-cols-2"><Toggle label="Documento aun vigente" description="Actualiza documento y biometria si vencio." checked={config.requireValidDocument} onChange={(requireValidDocument) => setConfig({ ...config, requireValidDocument })} /><Toggle label="Mismo espacio de trabajo" description="La identidad queda aislada por tenant." checked={config.requireSameTenant} onChange={(requireSameTenant) => setConfig({ ...config, requireSameTenant })} /><Toggle label="Sin alertas posteriores" description="Escala si existen incidentes o suplantacion." checked={config.requireNoAlerts} onChange={(requireNoAlerts) => setConfig({ ...config, requireNoAlerts })} /><Toggle label="Nivel suficiente" description="Exige un nivel igual o superior al actual." checked={config.requireSufficientLevel} onChange={(requireSufficientLevel) => setConfig({ ...config, requireSufficientLevel })} /></div><Info>La decision de reutilizar, revalidar o escalar se conservara como evidencia explicita de la sesion.</Info></div>; }

function IdentityStep({ config, setConfig }: StepProps) { return <div className="space-y-6"><SectionTitle title="Captura y prueba de vida" description="La captura facial, PAD y videoconsentimiento son comprobaciones independientes." /><CheckGroup title="Captura facial" options={['Selfie fotografica','Video corto','Captura automatica','Frontal y perfiles','Camara trasera asistida']} selected={config.captureModes} onChange={(captureModes) => setConfig({ ...config, captureModes })} /><div><Label>Prueba de vida</Label><div className="grid gap-2 md:grid-cols-2">{([['passive','Pasiva','Menor friccion para procesos estandar.'],['active','Activa','Desafios aleatorios frente a la camara.'],['hybrid','Hibrida recomendada','Escala a desafio solo cuando hay riesgo.'],['assisted','Videollamada asistida','Validacion en tiempo real por un analista.']] as const).map(([value,title,description]) => <button key={value} onClick={() => setConfig({ ...config, livenessMode: value })} className={`rounded-md border p-3 text-left ${config.livenessMode === value ? 'border-primary bg-blue-50' : 'border-slate-200'}`}><div className="flex items-center gap-2"><span className={`h-3.5 w-3.5 rounded-full border-4 ${config.livenessMode === value ? 'border-primary bg-white' : 'border-slate-300'}`} /><p className="text-sm font-600">{title}</p></div><p className="mt-1 pl-5 text-xs leading-5 text-slate-500">{description}</p></button>)}</div></div><CheckGroup title="Validaciones de captura" options={['Rostro completo','Nitidez e iluminacion','Una sola persona','Sin obstrucciones','Sin manipulacion evidente']} selected={config.livenessChecks} onChange={(livenessChecks) => setConfig({ ...config, livenessChecks })} /><CheckGroup title="Comparaciones independientes" options={['Documento vs. selfie','Enrolamiento vs. selfie','Autenticidad documental','Riesgo de dispositivo y sesion']} selected={config.comparisonChecks} onChange={(comparisonChecks) => setConfig({ ...config, comparisonChecks })} /><div className="grid gap-3 md:grid-cols-2"><Toggle label="Deteccion de inyeccion" description="Detecta camaras virtuales, replay o video sintetico." checked={config.injectionDetection} onChange={(injectionDetection) => setConfig({ ...config, injectionDetection })} /><Toggle label="Inteligencia de dispositivo" description="Emulador, root, jailbreak, VPN y riesgo." checked={config.deviceIntelligence} onChange={(deviceIntelligence) => setConfig({ ...config, deviceIntelligence })} /><Toggle label="OTP" description="Confirma control del correo o telefono." checked={config.otp} onChange={(otp) => setConfig({ ...config, otp })} /><Toggle label="Passkey" description="Reautentica identidades previamente enroladas." checked={config.passkey} onChange={(passkey) => setConfig({ ...config, passkey })} /></div></div>; }

function DocumentsStep({ config, setConfig }: StepProps) {
  const add = () => setConfig({ ...config, documents: [...config.documents, { id: crypto.randomUUID(), name: 'Nuevo requisito', subject: config.type === 'kyb' ? 'company' : 'individual', requirement: 'required', sides: 1, ocr: true, authenticity: true, expirationCheck: true }] });
  const update = (id: string, patch: Partial<IdentityDocumentRequirement>) => setConfig({ ...config, documents: config.documents.map((item) => item.id === id ? { ...item, ...patch } : item) });
  return <div className="space-y-5"><div className="flex items-start justify-between gap-3"><SectionTitle title="Constructor de requisitos" description="Define documentos obligatorios, opcionales o condicionales." /><button onClick={add} className="inline-flex h-9 flex-none items-center gap-2 rounded-md border border-primary px-3 text-xs font-600 text-primary"><Plus size={14} /> Agregar</button></div>{config.documents.length === 0 ? <button onClick={add} className="flex min-h-40 w-full flex-col items-center justify-center rounded-md border border-dashed border-slate-300 text-sm text-slate-500"><FileCheck2 size={24} className="mb-2 text-primary" />Agrega el primer requisito documental</button> : <div className="space-y-3">{config.documents.map((item) => <div key={item.id} className="rounded-md border border-slate-200 p-4"><div className="grid gap-3 md:grid-cols-[1fr_170px_170px_36px]"><Field label="Documento" value={item.name} onChange={(name) => update(item.id, { name })} /><Select label="Sujeto" value={item.subject} onChange={(subject) => update(item.id, { subject: subject as IdentityDocumentRequirement['subject'] })} options={[['individual','Persona fisica'],['company','Empresa'],['representative','Representante'],['beneficial_owner','Beneficiario controlador']]} /><Select label="Requisito" value={item.requirement} onChange={(requirement) => update(item.id, { requirement: requirement as IdentityDocumentRequirement['requirement'] })} options={[['required','Obligatorio'],['optional','Opcional'],['conditional','Condicional']]} /><button onClick={() => setConfig({ ...config, documents: config.documents.filter((current) => current.id !== item.id) })} aria-label="Eliminar requisito" className="mt-6 flex h-9 w-9 items-center justify-center rounded-md text-red-500 hover:bg-red-50"><Trash2 size={15} /></button></div><div className="mt-3 flex flex-wrap gap-4"><InlineCheck label="OCR" checked={item.ocr} onChange={(ocr) => update(item.id, { ocr })} /><InlineCheck label="Autenticidad" checked={item.authenticity} onChange={(authenticity) => update(item.id, { authenticity })} /><InlineCheck label="Vigencia" checked={item.expirationCheck} onChange={(expirationCheck) => update(item.id, { expirationCheck })} /><InlineCheck label="Dos caras" checked={item.sides === 2} onChange={(checked) => update(item.id, { sides: checked ? 2 : 1 })} /></div></div>)}</div>}</div>;
}

function ConsentStep({ config, setConfig }: StepProps) { return <div className="space-y-6"><SectionTitle title="Consentimientos versionados" description="La prueba de vida no sustituye la manifestacion de voluntad." /><div className="grid gap-3 md:grid-cols-2"><Toggle label="Aviso de privacidad" description="Finalidad, proveedor, conservacion y derechos." checked={config.privacyConsent} onChange={(privacyConsent) => setConfig({ ...config, privacyConsent })} /><Toggle label="Consentimiento biometrico" description="Control separado y expresamente aceptado." checked={config.biometricConsent} onChange={(biometricConsent) => setConfig({ ...config, biometricConsent })} /><Toggle label="Videoconsentimiento" description="Solo recomendado para politicas reforzadas." checked={config.videoConsent} onChange={(videoConsent) => setConfig({ ...config, videoConsent })} /></div>{config.videoConsent && <div className="rounded-lg border border-blue-100 bg-blue-50/40 p-4"><Select label="Modalidad" value={config.videoConsentMode} onChange={(videoConsentMode) => setConfig({ ...config, videoConsentMode: videoConsentMode as IdentityPolicyConfig['videoConsentMode'] })} options={[['silent','Aceptacion silenciosa'],['read_phrase','Lectura de frase'],['random_phrase','Frase aleatoria'],['questions','Preguntas dinamicas']]} /><div className="mt-4"><Label>Texto exacto presentado</Label><textarea value={config.videoConsentText} onChange={(event) => setConfig({ ...config, videoConsentText: event.target.value })} rows={4} className={`${inputClass} h-auto py-2`} /></div><p className="mt-3 text-xs leading-5 text-slate-500">Se vinculara al folio, hash SHA-256, participante, sesion, transcripcion y resultados biometricos.</p></div>}<div className="grid gap-4 md:grid-cols-2"><NumberField label="Retencion de evidencia" suffix="dias" value={config.retentionDays} onChange={(retentionDays) => setConfig({ ...config, retentionDays })} /></div><Info>Selfies, videos y plantillas biometricas se almacenan separados del repositorio documental ordinario y nunca se escriben en logs.</Info></div>; }

function ResultStep({ config, setConfig }: StepProps) { return <div className="space-y-6"><SectionTitle title="Motor de decision" description="Los valores son bandas UX; la calibracion final depende del proveedor biometrico." /><div className="grid gap-4 md:grid-cols-2"><NumberField label="Aprobacion automatica desde" suffix="puntos" value={config.autoApproveScore} onChange={(autoApproveScore) => setConfig({ ...config, autoApproveScore })} min={1} max={100} /><NumberField label="Revision manual desde" suffix="puntos" value={config.manualReviewScore} onChange={(manualReviewScore) => setConfig({ ...config, manualReviewScore })} min={1} max={100} /><NumberField label="Numero maximo de intentos" suffix="intentos" value={config.maxAttempts} onChange={(maxAttempts) => setConfig({ ...config, maxAttempts })} min={1} max={10} /></div><div className="grid gap-3 md:grid-cols-2"><Toggle label="Permitir reintento" description="Ofrece correcciones accionables al participante." checked={config.allowRetry} onChange={(allowRetry) => setConfig({ ...config, allowRetry })} /><Toggle label="Metodo alternativo" description="Permite escalar a revision o videollamada." checked={config.alternativeMethod} onChange={(alternativeMethod) => setConfig({ ...config, alternativeMethod })} /><Toggle label="Reporte PDF" description="Informe privado de verificacion de identidad." checked={config.generatePdfReport} onChange={(generatePdfReport) => setConfig({ ...config, generatePdfReport })} /><Toggle label="Paquete tecnico" description="Manifiesto, hashes, eventos y consentimientos." checked={config.generateEvidencePackage} onChange={(generateEvidencePackage) => setConfig({ ...config, generateEvidencePackage })} /><Toggle label="Sello de tiempo" description="Sella la integridad del reporte y manifiesto." checked={config.timestampEvidence} onChange={(timestampEvidence) => setConfig({ ...config, timestampEvidence })} /></div><div className="grid overflow-hidden rounded-lg border border-slate-200 md:grid-cols-3"><Decision tone="emerald" label="Aprobacion" value={`${config.autoApproveScore}–100`} /><Decision tone="amber" label="Revision" value={`${config.manualReviewScore}–${config.autoApproveScore - 1}`} /><Decision tone="red" label="No aprobada" value={`0–${config.manualReviewScore - 1}`} /></div></div>; }

type StepProps = { config: IdentityPolicyConfig; setConfig: (value: IdentityPolicyConfig) => void };
function SectionTitle({ title, description }: { title: string; description: string }) { return <div><h3 className="text-sm font-600 text-slate-950 dark:text-foreground">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div>; }
function Label({ children }: { children: React.ReactNode }) { return <label className="mb-1.5 block text-xs font-500 text-slate-600 dark:text-muted-foreground">{children}</label>; }
function Field({ label, value, onChange, placeholder = '' }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <div><Label>{label}</Label><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className={inputClass} /></div>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <div><Label>{label}</Label><select value={value} onChange={(event) => onChange(event.target.value)} className={inputClass}>{options.map(([optionValue, label]) => <option key={optionValue} value={optionValue}>{label}</option>)}</select></div>; }
function NumberField({ label, value, onChange, suffix, min = 0, max = 9999 }: { label: string; value: number; onChange: (value: number) => void; suffix: string; min?: number; max?: number }) { return <div><Label>{label}</Label><div className="flex h-10 overflow-hidden rounded-md border border-slate-200 bg-white focus-within:border-primary"><input type="number" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} className="min-w-0 flex-1 px-3 text-sm outline-none" /><span className="flex items-center border-l border-slate-200 bg-slate-50 px-3 text-xs text-slate-500">{suffix}</span></div></div>; }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <button type="button" onClick={() => onChange(!checked)} className={`flex min-h-20 w-full items-center gap-3 rounded-md border p-3 text-left transition ${checked ? 'border-blue-200 bg-blue-50/60' : 'border-slate-200 bg-white'}`}><span className={`relative h-5 w-9 flex-none rounded-full transition ${checked ? 'bg-primary' : 'bg-slate-300'}`}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white shadow-sm transition ${checked ? 'left-[18px]' : 'left-0.5'}`} /></span><span><span className="block text-sm font-600 text-slate-800">{label}</span><span className="mt-0.5 block text-xs leading-4 text-slate-500">{description}</span></span></button>; }
function CheckGroup({ title, options, selected, onChange }: { title: string; options: string[]; selected: string[]; onChange: (value: string[]) => void }) { return <div><Label>{title}</Label><div className="grid gap-2 md:grid-cols-2">{options.map((option) => <label key={option} className={`flex cursor-pointer items-center gap-2 rounded-md border px-3 py-2.5 text-sm ${selected.includes(option) ? 'border-blue-200 bg-blue-50 text-blue-800' : 'border-slate-200 text-slate-600'}`}><input type="checkbox" checked={selected.includes(option)} onChange={(event) => onChange(event.target.checked ? [...selected, option] : selected.filter((item) => item !== option))} className="h-4 w-4 rounded border-slate-300 text-primary" />{option}</label>)}</div></div>; }
function InlineCheck({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 rounded border-slate-300 text-primary" />{label}</label>; }
function Info({ children }: { children: React.ReactNode }) { return <div className="rounded-md border border-blue-100 bg-blue-50 px-4 py-3 text-xs leading-5 text-blue-700">{children}</div>; }
function Divider() { return <div className="border-t border-slate-200" />; }
function Summary({ label, value }: { label: string; value: React.ReactNode }) { return <div className="flex items-center justify-between border-b border-slate-200 px-3 py-2.5 last:border-0"><span className="text-xs text-slate-500">{label}</span><span className="text-xs font-600 text-slate-800 dark:text-foreground">{value}</span></div>; }
function Decision({ tone, label, value }: { tone: 'emerald' | 'amber' | 'red'; label: string; value: string }) { const colors = { emerald: 'bg-emerald-50 text-emerald-700', amber: 'bg-amber-50 text-amber-700', red: 'bg-red-50 text-red-700' }; return <div className={`border-b border-slate-200 p-4 text-center last:border-0 md:border-b-0 md:border-r ${colors[tone]}`}><p className="text-xs font-600">{label}</p><p className="mt-1 text-xl font-600 tabular-nums">{value}</p></div>; }
function labelAssurance(value: IdentityPolicyConfig['assuranceLevel']) { return ({ basic: 'Basico', standard: 'Estandar', enhanced: 'Reforzado', custom: 'Personalizado' })[value]; }
function TestDialog({ config, onClose }: { config: IdentityPolicyConfig; onClose: () => void }) { const checks = [{ label: 'Politica identificable', ok: Boolean(config.name.trim()) }, { label: 'Consentimiento de privacidad', ok: config.privacyConsent }, { label: 'Consentimiento biometrico', ok: config.biometricConsent }, { label: 'Prueba de vida configurada', ok: Boolean(config.livenessMode) }, { label: 'Evidencia verificable', ok: config.generatePdfReport || config.generateEvidencePackage }]; return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/35 p-4"><div className="w-full max-w-md rounded-lg border border-slate-200 bg-white p-5 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-base font-600">Prueba de configuracion</h2><p className="mt-1 text-xs text-slate-500">Simulacion previa a publicar la politica.</p></div><button onClick={onClose} className="text-xs text-slate-500">Cerrar</button></div><div className="mt-5 space-y-2">{checks.map((item) => <div key={item.label} className="flex items-center justify-between rounded-md border border-slate-200 px-3 py-2.5"><span className="text-sm text-slate-700">{item.label}</span>{item.ok ? <CheckCircle2 size={17} className="text-emerald-600" /> : <AlertTriangle size={17} className="text-amber-500" />}</div>)}</div><button onClick={onClose} className="mt-5 h-9 w-full rounded-md bg-primary text-sm font-600 text-white">Entendido</button></div></div>; }
