'use client';

import { useMemo, useRef, useState } from 'react';
import {
  AlertCircle, ArrowLeft, ArrowRight, Camera, Check, CheckCircle2, ChevronRight, Circle,
  Clock3, Download, FileCheck2, FileText, Fingerprint, HelpCircle, LockKeyhole, PenLine,
  Save, ShieldCheck, Signature, Upload, UserRound,
} from 'lucide-react';
import AppLogo from '@/components/ui/AppLogo';
import { createDemoCaseFile, type CaseRequirement } from '@/lib/case-files/schema';

type GuestStep = 'welcome' | 'checklist' | 'document' | 'forms' | 'identity' | 'signature' | 'review' | 'success';

export default function GuestCaseFilePage() {
  const caseFile = createDemoCaseFile();
  const [step, setStep] = useState<GuestStep>('welcome');
  const [selectedDocument, setSelectedDocument] = useState<CaseRequirement | null>(null);
  const [uploaded, setUploaded] = useState<Record<string, string>>({});
  const [identityConfirmed, setIdentityConfirmed] = useState(false);
  const [signatureAccepted, setSignatureAccepted] = useState(false);

  const checklist = useMemo(() => caseFile.requirements.filter((item) => item.required).slice(0, 6), [caseFile.requirements]);
  const completed = checklist.filter((item) => item.status === 'approved' || uploaded[item.id]).length;
  const progress = Math.round((completed / checklist.length) * 70 + (identityConfirmed ? 15 : 0) + (signatureAccepted ? 15 : 0));

  const openDocument = (document: CaseRequirement) => { setSelectedDocument(document); setStep('document'); };
  const back = () => setStep(step === 'document' ? 'checklist' : 'welcome');

  return <div className="min-h-screen bg-[#F8F8FB] text-[#18181B]">
    <header className="sticky top-0 z-30 border-b border-[#EBEBF0] bg-white"><div className="mx-auto flex h-16 max-w-3xl items-center justify-between px-4"><AppLogo className="w-[122px]" /><span className="inline-flex items-center gap-1.5 text-xs font-medium text-[#52525B]"><LockKeyhole size={14} className="text-emerald-600" />Acceso seguro</span></div></header>
    {step !== 'welcome' && step !== 'success' && <div className="border-b border-[#EBEBF0] bg-white"><div className="mx-auto max-w-3xl px-4 py-3"><div className="flex items-center justify-between text-xs"><span className="font-medium">Tu progreso</span><span className="font-semibold text-[#4F46E5]">{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-zinc-100"><div className="h-full rounded-full bg-[#4F46E5] transition-all" style={{ width: `${progress}%` }} /></div></div></div>}

    <main className="mx-auto max-w-3xl px-4 py-6 md:py-10">
      {step === 'welcome' && <Welcome caseFile={caseFile} onStart={() => setStep('checklist')} />}
      {step === 'checklist' && <Checklist caseFile={caseFile} items={checklist} uploaded={uploaded} onOpen={openDocument} onForms={() => setStep('forms')} onIdentity={() => setStep('identity')} onSignature={() => setStep('signature')} onReview={() => setStep('review')} />}
      {step === 'document' && selectedDocument && <DocumentUpload item={selectedDocument} uploadedName={uploaded[selectedDocument.id]} onBack={back} onUploaded={(name) => { setUploaded({ ...uploaded, [selectedDocument.id]: name }); setStep('checklist'); }} />}
      {step === 'forms' && <GuestForms forms={caseFile.forms} onBack={() => setStep('checklist')} />}
      {step === 'identity' && <GuestIdentity confirmed={identityConfirmed} onBack={() => setStep('checklist')} onConfirm={() => { setIdentityConfirmed(true); setStep('checklist'); }} />}
      {step === 'signature' && <GuestSignature accepted={signatureAccepted} onBack={() => setStep('checklist')} onAccept={() => { setSignatureAccepted(true); setStep('checklist'); }} />}
      {step === 'review' && <GuestReview caseFile={caseFile} progress={progress} onBack={() => setStep('checklist')} onSubmit={() => setStep('success')} />}
      {step === 'success' && <GuestSuccess folio={caseFile.folio} />}
    </main>
  </div>;
}

function Welcome({ caseFile, onStart }: { caseFile: ReturnType<typeof createDemoCaseFile>; onStart: () => void }) { return <div className="overflow-hidden rounded-md border border-[#EBEBF0] bg-white"><div className="border-b border-[#EBEBF0] p-5 text-center md:p-8"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#EEF2FF] text-[#4F46E5]"><FileCheck2 size={25} /></span><p className="mt-5 text-xs font-semibold uppercase text-[#4F46E5]">Expediente digital</p><h1 className="mt-1 text-2xl font-semibold">Completa tu expediente</h1><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-[#52525B]">Has sido invitado a integrar <strong>{caseFile.title}</strong>. Te guiaremos paso a paso; no necesitas crear una cuenta.</p></div><div className="p-5 md:p-8"><div className="grid gap-3 sm:grid-cols-2"><Info icon={Clock3} title="Tiempo estimado" detail="8 a 12 minutos" /><Info icon={ShieldCheck} title="Acceso protegido" detail="Enlace seguro + OTP" /></div><div className="mt-6 rounded-md bg-[#F8F8FB] p-4"><p className="text-sm font-semibold">Ten a la mano</p><ul className="mt-3 space-y-2">{['Identificación oficial', 'Constancia fiscal', 'Comprobante de domicilio', 'Carátula bancaria'].map((item) => <li key={item} className="flex items-center gap-2 text-sm text-[#52525B]"><Circle size={12} className="text-[#4F46E5]" />{item}</li>)}</ul></div><button onClick={onStart} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-md bg-[#4F46E5] text-sm font-semibold text-white">Comenzar <ArrowRight size={16} /></button><button className="mt-3 flex h-11 w-full items-center justify-center gap-2 rounded-md text-sm font-medium text-[#52525B]"><Save size={15} /> Continuar después</button></div></div>; }

function Checklist({ caseFile, items, uploaded, onOpen, onForms, onIdentity, onSignature, onReview }: { caseFile: ReturnType<typeof createDemoCaseFile>; items: CaseRequirement[]; uploaded: Record<string,string>; onOpen: (item: CaseRequirement) => void; onForms: () => void; onIdentity: () => void; onSignature: () => void; onReview: () => void }) { return <div><div className="mb-5"><p className="text-sm text-[#71717A]">Hola, José Alberto</p><h1 className="mt-1 text-2xl font-semibold">Tu checklist</h1><p className="mt-1 text-sm text-[#52525B]">Completa los pasos pendientes. Guardamos tu avance automáticamente.</p></div>{caseFile.observations.some((item) => item.status === 'open') && <div className="mb-5 rounded-md border border-red-200 bg-red-50 p-4"><div className="flex gap-3"><AlertCircle size={18} className="mt-0.5 text-red-600" /><div><p className="text-sm font-semibold text-red-800">Tienes una corrección pendiente</p><p className="mt-1 text-xs leading-5 text-red-700">La opinión de cumplimiento debe corresponder al mes en curso. Te indicamos cómo resolverlo dentro del requisito.</p></div></div></div>}<div className="space-y-3">{items.map((item) => { const done = item.status === 'approved' || Boolean(uploaded[item.id]); const observed = item.status === 'observed'; return <button key={item.id} onClick={() => onOpen(item)} className={`flex w-full items-center gap-3 rounded-md border bg-white p-4 text-left transition ${observed ? 'border-red-200' : done ? 'border-emerald-200' : 'border-[#EBEBF0]'}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full ${observed ? 'bg-red-50 text-red-600' : done ? 'bg-emerald-50 text-emerald-600' : 'bg-zinc-100 text-zinc-400'}`}>{observed ? <AlertCircle size={17} /> : done ? <Check size={17} /> : <FileText size={16} />}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{item.name}</span><span className={`mt-0.5 block text-xs ${observed ? 'text-red-600' : 'text-[#71717A]'}`}>{observed ? 'Requiere corrección' : done ? 'Completado' : 'Pendiente de carga'}</span></span><ChevronRight size={16} className="text-[#A1A1AA]" /></button>; })}<ChecklistAction icon={FileText} label="Formularios" detail={`${caseFile.forms.filter((item) => item.status === 'approved').length} de ${caseFile.forms.length} completados`} onClick={onForms} /><ChecklistAction icon={Fingerprint} label="Valida tu identidad" detail="Acreditamiento requerido" onClick={onIdentity} /><ChecklistAction icon={Signature} label="Firma de autorización" detail="2 documentos pendientes" onClick={onSignature} /></div><button onClick={onReview} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-md bg-[#18181B] text-sm font-semibold text-white">Revisar y enviar <ArrowRight size={16} /></button><button className="mt-3 flex h-10 w-full items-center justify-center gap-2 text-sm text-[#52525B]"><HelpCircle size={15} /> Necesito ayuda</button></div>; }

function DocumentUpload({ item, uploadedName, onBack, onUploaded }: { item: CaseRequirement; uploadedName?: string; onBack: () => void; onUploaded: (name: string) => void }) { const inputRef = useRef<HTMLInputElement>(null); const [fileName, setFileName] = useState(uploadedName || ''); return <div><Back onClick={onBack} /><p className="text-xs font-semibold uppercase text-[#4F46E5]">Documento</p><h1 className="mt-1 text-2xl font-semibold">{item.name}</h1><p className="mt-2 text-sm leading-6 text-[#52525B]">{item.description}</p>{item.rejectionReason && <div className="mt-5 rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700"><p className="font-semibold">Qué está mal</p><p className="mt-1">{item.rejectionReason}</p><p className="mt-3 font-semibold">Cómo corregirlo</p><p className="mt-1">{item.correctionAction}</p></div>}<div className="mt-6 rounded-md border border-[#EBEBF0] bg-white p-4"><button onClick={() => inputRef.current?.click()} className="flex min-h-52 w-full flex-col items-center justify-center rounded-md border border-dashed border-[#C7D2FE] bg-[#F8F8FB] p-6 text-center"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-[#EEF2FF] text-[#4F46E5]"><Upload size={20} /></span><p className="mt-4 text-sm font-semibold">{fileName || 'Selecciona un archivo'}</p><p className="mt-1 text-xs text-[#71717A]">PDF, JPG o PNG · máximo {item.maxSizeMb} MB</p></button><input ref={inputRef} type="file" accept="application/pdf,image/jpeg,image/png" className="hidden" onChange={(event) => setFileName(event.target.files?.[0]?.name || '')} /><button onClick={() => inputRef.current?.click()} className="mt-3 flex h-11 w-full items-center justify-center gap-2 rounded-md border border-[#EBEBF0] text-sm font-semibold"><Camera size={16} /> Tomar foto o buscar archivo</button></div><button onClick={() => fileName && onUploaded(fileName)} disabled={!fileName} className="mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-md bg-[#4F46E5] text-sm font-semibold text-white disabled:bg-[#D4D4D8]">Guardar documento <ArrowRight size={16} /></button></div>; }

function GuestForms({ forms, onBack }: { forms: ReturnType<typeof createDemoCaseFile>['forms']; onBack: () => void }) { return <div><Back onClick={onBack} /><p className="text-xs font-semibold uppercase text-[#4F46E5]">Formularios</p><h1 className="mt-1 text-2xl font-semibold">Completa tus datos</h1><p className="mt-2 text-sm text-[#52525B]">Cada formulario guarda tu avance y generará un PDF para tu revisión.</p><div className="mt-6 space-y-3">{forms.map((form) => <button key={form.id} className="flex w-full items-center gap-3 rounded-md border border-[#EBEBF0] bg-white p-4 text-left"><span className={`flex h-9 w-9 items-center justify-center rounded-full ${form.status === 'approved' ? 'bg-emerald-50 text-emerald-600' : 'bg-[#EEF2FF] text-[#4F46E5]'}`}>{form.status === 'approved' ? <Check size={16} /> : <FileText size={16} />}</span><span className="flex-1"><span className="block text-sm font-semibold">{form.name}</span><span className="text-xs text-[#71717A]">{form.status === 'approved' ? 'Completado' : form.status === 'in_progress' ? 'Continuar formulario' : 'Iniciar formulario'}</span></span><ChevronRight size={16} className="text-[#A1A1AA]" /></button>)}</div></div>; }

function GuestIdentity({ confirmed, onBack, onConfirm }: { confirmed: boolean; onBack: () => void; onConfirm: () => void }) { return <div><Back onClick={onBack} /><p className="text-xs font-semibold uppercase text-[#4F46E5]">Identidad</p><h1 className="mt-1 text-2xl font-semibold">Valida tu identidad</h1><p className="mt-2 text-sm text-[#52525B]">Usaremos estas evidencias únicamente para acreditar que eres la persona que integra y firma el expediente.</p><div className="mt-6 rounded-md border border-[#EBEBF0] bg-white p-5"><StepRow number="1" title="Identificación oficial" detail="Toma una foto clara por ambos lados" done /><StepRow number="2" title="Selfie" detail="Confirma que eres el titular" done /><StepRow number="3" title="Confirma tus datos" detail="Revisa nombre, CURP y RFC" done={confirmed} /></div><button onClick={onConfirm} className="mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-md bg-[#4F46E5] text-sm font-semibold text-white"><Fingerprint size={17} /> Confirmar identidad</button></div>; }

function GuestSignature({ accepted, onBack, onAccept }: { accepted: boolean; onBack: () => void; onAccept: () => void }) { const [consent, setConsent] = useState(accepted); return <div><Back onClick={onBack} /><p className="text-xs font-semibold uppercase text-[#4F46E5]">Firma</p><h1 className="mt-1 text-2xl font-semibold">Documento listo para firma</h1><p className="mt-2 text-sm text-[#52525B]">Contrato de prestación de servicios</p><div className="mt-6 rounded-md border border-[#EBEBF0] bg-white p-5"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-md bg-[#EEF2FF] text-[#4F46E5]"><FileText size={19} /></span><div><p className="text-sm font-semibold">Contrato de prestación de servicios</p><p className="text-xs text-[#71717A]">12 páginas · e.firma SAT</p></div></div><button className="mt-4 flex h-10 w-full items-center justify-center gap-2 rounded-md border border-[#EBEBF0] text-sm font-semibold"><FileText size={15} /> Ver documento</button><label className="mt-5 flex cursor-pointer items-start gap-3 rounded-md bg-[#F8F8FB] p-4"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-0.5 h-4 w-4 rounded border-zinc-300 text-[#4F46E5]" /><span className="text-sm leading-5">He leído el documento y acepto usar medios electrónicos para firmarlo.</span></label></div><button onClick={onAccept} disabled={!consent} className="mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-md bg-[#18181B] text-sm font-semibold text-white disabled:bg-[#D4D4D8]"><PenLine size={17} /> Continuar a firma</button></div>; }

function GuestReview({ caseFile, progress, onBack, onSubmit }: { caseFile: ReturnType<typeof createDemoCaseFile>; progress: number; onBack: () => void; onSubmit: () => void }) { return <div><Back onClick={onBack} /><p className="text-xs font-semibold uppercase text-[#4F46E5]">Revisión final</p><h1 className="mt-1 text-2xl font-semibold">Confirma tu envío</h1><p className="mt-2 text-sm text-[#52525B]">Revisa que todo esté correcto antes de enviar el expediente al equipo.</p><div className="mt-6 rounded-md border border-[#EBEBF0] bg-white p-5"><div className="flex items-center justify-between"><span className="text-sm font-semibold">Avance del expediente</span><span className="text-lg font-semibold text-[#4F46E5]">{progress}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-zinc-100"><div className="h-full rounded-full bg-[#4F46E5]" style={{ width: `${progress}%` }} /></div><div className="mt-5 space-y-3"><ReviewLine label="Documentos recibidos" value={`${caseFile.requirements.filter((item) => item.status !== 'pending').length} archivos`} /><ReviewLine label="Formularios" value={`${caseFile.forms.length} vinculados`} /><ReviewLine label="Identidad" value="Acreditada" /><ReviewLine label="Firmas" value="Evidencia preparada" /></div></div><button onClick={onSubmit} className="mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-md bg-emerald-600 text-sm font-semibold text-white"><CheckCircle2 size={17} /> Enviar a revisión</button></div>; }

function GuestSuccess({ folio }: { folio: string }) { return <div className="rounded-md border border-[#EBEBF0] bg-white p-6 text-center md:p-10"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><Check size={28} /></span><h1 className="mt-5 text-2xl font-semibold">Expediente enviado a revisión</h1><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-[#52525B]">Recibimos tu información. Te notificaremos si algún documento necesita una corrección.</p><div className="mx-auto mt-6 max-w-sm rounded-md bg-[#F8F8FB] p-4"><p className="text-xs text-[#71717A]">Folio de seguimiento</p><p className="mt-1 text-lg font-semibold">{folio}</p></div><button className="mt-6 inline-flex h-11 items-center justify-center gap-2 rounded-md border border-[#EBEBF0] px-5 text-sm font-semibold"><Download size={15} /> Descargar acuse de recepción</button><p className="mt-8 text-xs text-[#A1A1AA]">Este envío quedó registrado con fecha, hora, IP y hash de integridad.</p></div>; }

function ChecklistAction({ icon: Icon, label, detail, onClick }: { icon: typeof FileText; label: string; detail: string; onClick: () => void }) { return <button onClick={onClick} className="flex w-full items-center gap-3 rounded-md border border-[#EBEBF0] bg-white p-4 text-left"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#EEF2FF] text-[#4F46E5]"><Icon size={16} /></span><span className="flex-1"><span className="block text-sm font-semibold">{label}</span><span className="text-xs text-[#71717A]">{detail}</span></span><ChevronRight size={16} className="text-[#A1A1AA]" /></button>; }
function Info({ icon: Icon, title, detail }: { icon: typeof Clock3; title: string; detail: string }) { return <div className="flex items-center gap-3 rounded-md border border-[#EBEBF0] p-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#EEF2FF] text-[#4F46E5]"><Icon size={16} /></span><span><span className="block text-xs text-[#71717A]">{title}</span><span className="text-sm font-semibold">{detail}</span></span></div>; }
function Back({ onClick }: { onClick: () => void }) { return <button onClick={onClick} className="mb-5 inline-flex items-center gap-1.5 text-sm font-medium text-[#52525B]"><ArrowLeft size={15} /> Regresar</button>; }
function StepRow({ number, title, detail, done }: { number: string; title: string; detail: string; done: boolean }) { return <div className="flex gap-3 border-b border-[#EBEBF0] py-4 first:pt-0 last:border-0 last:pb-0"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-semibold ${done ? 'bg-emerald-50 text-emerald-600' : 'bg-[#EEF2FF] text-[#4F46E5]'}`}>{done ? <Check size={14} /> : number}</span><span><span className="block text-sm font-semibold">{title}</span><span className="text-xs text-[#71717A]">{detail}</span></span></div>; }
function ReviewLine({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 text-sm"><span className="text-[#52525B]">{label}</span><span className="font-semibold">{value}</span></div>; }
