'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, CalendarDays, Check, CheckCircle2, ClipboardCheck, FileText, Flag, FolderKanban, Loader2, Plus, ShieldCheck, Trash2, UserRound, UsersRound } from 'lucide-react';
import AppLogo from '@/components/ui/AppLogo';
import { createClient } from '@/lib/supabase/client';
import { useWorkspace } from '@/contexts/WorkspaceContext';
import { useAuth } from '@/contexts/AuthContext';
import { buildInitialCaseFromTemplate, CASE_TEMPLATES, type CaseParticipant, type CasePriority, type CaseSensitivity } from '@/lib/case-files/schema';

const steps = [
  { title: 'Datos generales', icon: FolderKanban }, { title: 'Participantes', icon: UsersRound },
  { title: 'Documentos', icon: FileText }, { title: 'Formularios', icon: ClipboardCheck },
  { title: 'Identidad', icon: ShieldCheck }, { title: 'Hitos', icon: Flag }, { title: 'Reglas de cierre', icon: CheckCircle2 },
];

export default function NuevoExpedientePage() {
  const router = useRouter();
  const { activeWorkspace } = useWorkspace();
  const { user } = useAuth();
  const [step, setStep] = useState(0);
  const [templateId, setTemplateId] = useState(CASE_TEMPLATES[0].id);
  const [draft, setDraft] = useState(() => buildInitialCaseFromTemplate(CASE_TEMPLATES[0]));
  const [forms, setForms] = useState<{ id: string; name: string }[]>([]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!activeWorkspace?.id) return;
    createClient().from('form_templates').select('id,name').eq('workspace_id', activeWorkspace.id).eq('status', 'published').then(({ data }) => setForms(data || []));
  }, [activeWorkspace?.id]);

  const selectTemplate = (id: string) => {
    const template = CASE_TEMPLATES.find((item) => item.id === id) || CASE_TEMPLATES[0];
    setTemplateId(id);
    setDraft((current) => ({ ...buildInitialCaseFromTemplate(template), title: current.title, participant: current.participant, responsible: current.responsible, responsibleArea: current.responsibleArea, targetCloseAt: current.targetCloseAt, description: current.description }));
  };

  const validation = useMemo(() => {
    if (step === 0 && (!draft.title.trim() || !draft.participant.trim() || !draft.responsible.trim())) return 'Completa el nombre, la contraparte y el responsable.';
    if (step === 1 && draft.participants.length === 0) return 'Agrega al menos un participante.';
    if (step === 2 && !draft.requirements.some((item) => item.required)) return 'Conserva al menos un documento obligatorio.';
    if (step === 4 && draft.identityMethods.length === 0) return 'Selecciona una validación de identidad o marca “Sin validación”.';
    return '';
  }, [draft, step]);

  const next = () => { if (validation) { setError(validation); return; } setError(''); setStep((current) => Math.min(6, current + 1)); };
  const previous = () => { setError(''); setStep((current) => Math.max(0, current - 1)); };

  const createCase = async () => {
    if (!activeWorkspace?.id || !user?.id) { setError('No se encontró un espacio de trabajo activo.'); return; }
    setSaving(true); setError('');
    const supabase = createClient();
    const { data: folioData } = await supabase.rpc('next_case_file_folio', { target_workspace: activeWorkspace.id });
    const folio = folioData || `EXP-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;
    const { data: caseFile, error: caseError } = await supabase.from('case_files').insert({
      workspace_id: activeWorkspace.id, folio, title: draft.title, description: draft.description,
      case_type: draft.caseType, case_subtype: draft.caseSubtype || null, subject_name: draft.participant,
      status: 'open', priority: draft.priority, sensitivity_level: draft.sensitivity,
      responsible_area: draft.responsibleArea, owner_user_id: user.id, opened_at: new Date().toISOString(),
      target_close_at: draft.targetCloseAt || null, created_by: user.id,
    }).select('id').single();
    if (caseError || !caseFile) {
      setSaving(false);
      router.push('/expedientes/demo-supplier?created=local');
      return;
    }
    const base = { workspace_id: activeWorkspace.id, case_file_id: caseFile.id };
    await Promise.all([
      draft.participants.length ? supabase.from('case_file_participants').insert(draft.participants.map((item) => ({ ...base, name: item.name, participant_type: item.role, role: item.role, email: item.email, rfc: item.rfc || null, access_method: item.accessMethod, status: 'pending' }))) : Promise.resolve(),
      supabase.from('case_file_requirements').insert(draft.requirements.map((item, index) => ({ ...base, title: item.name, description: item.description, category: item.category, sort_order: index, is_required: item.required, allowed_mime_types: item.allowedFormats.map(formatToMime), max_size_bytes: item.maxSizeMb * 1024 * 1024, requires_manual_review: item.requiresReview, requires_signature: item.requiresSignature, requires_identity: item.requiresIdentity }))),
      draft.milestones.length ? supabase.from('case_file_milestones').insert(draft.milestones.map((item, index) => ({ ...base, title: item.title, description: item.description, sort_order: index, status: item.status, responsible_label: item.responsible, completion_condition_json: { label: item.condition } }))) : Promise.resolve(),
      draft.formIds.length ? supabase.from('case_file_forms').insert(draft.formIds.map((formId) => ({ ...base, form_template_id: formId, title: forms.find((item) => item.id === formId)?.name || 'Formulario', status: 'not_started' }))) : Promise.resolve(),
    ]);
    setSaving(false);
    router.push(`/expedientes/${caseFile.id}`);
  };

  return <div className="min-h-screen bg-[#f6f8fb] text-slate-950 dark:bg-background dark:text-foreground">
    <header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-slate-200 bg-white px-4 dark:border-border dark:bg-card md:px-6">
      <div className="flex items-center gap-4"><button onClick={() => router.push('/expedientes')} aria-label="Salir del wizard" className="flex h-9 w-9 items-center justify-center rounded-md border border-slate-200 text-slate-600 transition hover:bg-slate-50 dark:border-border"><ArrowLeft size={17} /></button><AppLogo className="[&_img]:h-auto [&_img]:w-[126px]" /><div className="hidden h-8 w-px bg-slate-200 md:block" /><div className="hidden md:block"><p className="text-sm font-semibold">Nuevo expediente</p><p className="text-xs text-slate-500">Apertura guiada y verificable</p></div></div>
      <div className="text-right"><p className="text-xs font-medium text-slate-600">Paso {step + 1} de {steps.length}</p><div className="mt-1.5 h-1.5 w-32 overflow-hidden rounded-full bg-slate-100 md:w-52"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div></div>
    </header>

    <div className="mx-auto grid max-w-[1500px] md:grid-cols-[252px_minmax(0,1fr)]">
      <aside className="hidden min-h-[calc(100vh-72px)] border-r border-slate-200 bg-white p-4 dark:border-border dark:bg-card md:block"><p className="mb-3 px-2 text-[11px] font-semibold uppercase text-slate-400">Configuración</p><ol className="space-y-1">{steps.map((item, index) => { const Icon = item.icon; const active = index === step; const done = index < step; return <li key={item.title}><button onClick={() => index < step && setStep(index)} className={`flex h-11 w-full items-center gap-3 rounded-md px-3 text-left text-sm transition ${active ? 'bg-blue-50 font-semibold text-primary' : done ? 'text-slate-700 hover:bg-slate-50' : 'cursor-default text-slate-400'}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full border text-[11px] ${done ? 'border-emerald-500 bg-emerald-500 text-white' : active ? 'border-primary bg-white text-primary' : 'border-slate-200'}`}>{done ? <Check size={13} /> : <Icon size={13} />}</span>{item.title}</button></li>; })}</ol></aside>

      <main className="min-w-0 px-4 py-6 md:px-8 md:py-8 lg:px-12"><div className="mx-auto max-w-4xl"><div className="mb-6"><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-primary"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-blue-50">{step + 1}</span>{steps[step].title}</div><h1 className="text-2xl font-semibold">{stepTitles[step]}</h1><p className="mt-1 text-sm leading-6 text-slate-500 dark:text-muted-foreground">{stepDescriptions[step]}</p></div>
        <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/30 dark:border-border dark:bg-card md:p-6">{step === 0 && <GeneralStep draft={draft} setDraft={setDraft} templateId={templateId} selectTemplate={selectTemplate} />}{step === 1 && <ParticipantsStep participants={draft.participants} onChange={(participants) => setDraft({ ...draft, participants })} />}{step === 2 && <DocumentsStep requirements={draft.requirements} onChange={(requirements: typeof draft.requirements) => setDraft({ ...draft, requirements })} />}{step === 3 && <FormsStep forms={forms} selected={draft.formIds} onChange={(formIds) => setDraft({ ...draft, formIds })} />}{step === 4 && <IdentityStep selected={draft.identityMethods} onChange={(identityMethods) => setDraft({ ...draft, identityMethods })} />}{step === 5 && <MilestonesStep milestones={draft.milestones} onChange={(milestones: typeof draft.milestones) => setDraft({ ...draft, milestones })} />}{step === 6 && <ClosureStep draft={draft} />}</section>
        {error && <div className="mt-4 rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
        <footer className="mt-6 flex items-center justify-between"><button onClick={previous} disabled={step === 0} className="inline-flex h-10 items-center gap-2 rounded-md border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-600 transition hover:bg-slate-50 disabled:opacity-0 dark:border-border"><ArrowLeft size={15} /> Atrás</button>{step < 6 ? <button onClick={next} className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90">Guardar y continuar <ArrowRight size={15} /></button> : <button onClick={createCase} disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-md bg-emerald-600 px-5 text-sm font-semibold text-white transition hover:bg-emerald-700 disabled:opacity-60">{saving ? <Loader2 size={15} className="animate-spin" /> : <ShieldCheck size={15} />} Abrir expediente</button>}</footer>
      </div></main>
    </div>
  </div>;
}

const stepTitles = ['Define el expediente', '¿Quiénes participan?', '¿Qué documentos se necesitan?', 'Vincula formularios', 'Define el acreditamiento', 'Configura el seguimiento', 'Confirma las condiciones de cierre'];
const stepDescriptions = ['Selecciona una plantilla y registra la información mínima para abrirlo.', 'Agrega solo a quienes tendrán una función dentro del expediente.', 'Conserva un checklist breve, claro y revisable.', 'Los formularios generarán su PDF desde el mismo esquema.', 'Elige las comprobaciones proporcionales al riesgo.', 'Los hitos muestran qué sigue y qué está bloqueando el avance.', 'Estas condiciones se validarán antes del cierre hermético.'];

function GeneralStep({ draft, setDraft, templateId, selectTemplate }: any) { return <div className="space-y-6"><div><Label>Plantilla del expediente</Label><div className="grid gap-3 md:grid-cols-3">{CASE_TEMPLATES.map((template) => <button key={template.id} onClick={() => selectTemplate(template.id)} className={`rounded-md border p-4 text-left transition ${templateId === template.id ? 'border-[#1E6BFF] bg-[#EFF6FF]' : 'border-[#E2E8F0] hover:border-[#BFDBFE] dark:border-border'}`}><span className="text-sm font-semibold">{template.name}</span><p className="mt-1 text-xs leading-5 text-[#64748B]">{template.description}</p></button>)}</div></div><div className="grid gap-4 md:grid-cols-2"><Field label="Nombre del expediente" value={draft.title} onChange={(title) => setDraft({ ...draft, title })} placeholder="Alta de proveedor · Empresa" /><Field label="Cliente, proveedor o contraparte" value={draft.participant} onChange={(participant) => setDraft({ ...draft, participant })} placeholder="Razón social o nombre" /><Field label="Responsable interno" value={draft.responsible} onChange={(responsible) => setDraft({ ...draft, responsible })} placeholder="Nombre del responsable" /><Field label="Área responsable" value={draft.responsibleArea} onChange={(responsibleArea) => setDraft({ ...draft, responsibleArea })} placeholder="Legal y Cumplimiento" /><Field label="Fecha objetivo de cierre" type="date" value={draft.targetCloseAt} onChange={(targetCloseAt) => setDraft({ ...draft, targetCloseAt })} /><SelectField label="Prioridad" value={draft.priority} onChange={(priority) => setDraft({ ...draft, priority: priority as CasePriority })} options={[['low','Baja'],['normal','Normal'],['high','Alta'],['urgent','Urgente']]} /><SelectField label="Sensibilidad" value={draft.sensitivity} onChange={(sensitivity) => setDraft({ ...draft, sensitivity: sensitivity as CaseSensitivity })} options={[['standard','Estándar'],['confidential','Confidencial'],['highly_confidential','Altamente confidencial']]} /></div><div><Label>Descripción</Label><textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} rows={3} placeholder="Propósito y alcance del expediente" className={inputClass} /></div></div>; }

function ParticipantsStep({ participants, onChange }: { participants: CaseParticipant[]; onChange: (value: CaseParticipant[]) => void }) { const add = () => onChange([...participants, { id: crypto.randomUUID(), name: '', role: 'Invitado externo', email: '', accessMethod: 'secure_link_otp', status: 'pending' }]); return <div><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-semibold">Participantes</h2><p className="text-xs text-[#64748B]">El acceso externo recomendado utiliza enlace seguro y OTP.</p></div><button onClick={add} className="inline-flex h-9 items-center gap-2 rounded-md border border-[#1E6BFF] px-3 text-xs font-semibold text-[#1E6BFF]"><Plus size={14} /> Agregar</button></div>{participants.length === 0 ? <button onClick={add} className="flex min-h-40 w-full flex-col items-center justify-center rounded-md border border-dashed border-[#CBD5E1] text-sm text-[#64748B]"><UserRound size={22} className="mb-2 text-[#1E6BFF]" />Agrega a la persona que integrará el expediente</button> : <div className="space-y-3">{participants.map((participant, index) => <div key={participant.id} className="grid gap-3 rounded-md border border-[#E2E8F0] p-4 dark:border-border md:grid-cols-[1fr_1fr_190px_36px]"><Field label="Nombre o razón social" value={participant.name} onChange={(name) => onChange(participants.map((item, itemIndex) => itemIndex === index ? { ...item, name } : item))} /><Field label="Correo" type="email" value={participant.email} onChange={(email) => onChange(participants.map((item, itemIndex) => itemIndex === index ? { ...item, email } : item))} /><SelectField label="Rol" value={participant.role} onChange={(role) => onChange(participants.map((item, itemIndex) => itemIndex === index ? { ...item, role } : item))} options={[['Titular','Titular'],['Representante legal','Representante legal'],['Firmante','Firmante'],['Invitado externo','Invitado externo'],['Revisor','Revisor'],['Aprobador interno','Aprobador interno']]} /><button aria-label="Eliminar participante" onClick={() => onChange(participants.filter((_, itemIndex) => itemIndex !== index))} className="mt-6 flex h-9 w-9 items-center justify-center rounded-md text-red-500 hover:bg-red-50"><Trash2 size={15} /></button></div>)}</div>}</div>; }

function DocumentsStep({ requirements, onChange }: any) { return <div className="space-y-3">{requirements.map((item: any, index: number) => <div key={item.id} className="flex items-start gap-3 rounded-md border border-[#E2E8F0] p-4 dark:border-border"><input type="checkbox" checked={item.required} onChange={(event) => onChange(requirements.map((current: any, currentIndex: number) => currentIndex === index ? { ...current, required: event.target.checked } : current))} className="mt-1 h-4 w-4 rounded border-zinc-300 text-[#1E6BFF]" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{item.name}</p>{item.requiresSignature && <Tag>Requiere firma</Tag>}{item.requiresIdentity && <Tag>Identidad</Tag>}</div><p className="mt-1 text-xs text-[#64748B]">{item.description}</p><p className="mt-2 text-[11px] text-[#94A3B8]">{item.allowedFormats.join(', ')} · máximo {item.maxSizeMb} MB · {item.requiresReview ? 'revisión manual' : 'validación automática'}</p></div><span className={`text-xs font-medium ${item.required ? 'text-[#1E6BFF]' : 'text-[#94A3B8]'}`}>{item.required ? 'Obligatorio' : 'Opcional'}</span></div>)}</div>; }

function FormsStep({ forms, selected, onChange }: { forms: { id: string; name: string }[]; selected: string[]; onChange: (value: string[]) => void }) { if (!forms.length) return <div className="rounded-md border border-dashed border-[#CBD5E1] p-8 text-center"><ClipboardCheck size={24} className="mx-auto text-[#1E6BFF]" /><h3 className="mt-3 text-sm font-semibold">Aún no hay formularios publicados</h3><p className="mt-1 text-sm text-[#64748B]">Puedes abrir el expediente y vincular Formularios Firmables más adelante.</p></div>; return <div className="space-y-3">{forms.map((form) => <label key={form.id} className={`flex cursor-pointer items-center gap-3 rounded-md border p-4 ${selected.includes(form.id) ? 'border-[#1E6BFF] bg-[#EFF6FF]' : 'border-[#E2E8F0] dark:border-border'}`}><input type="checkbox" checked={selected.includes(form.id)} onChange={(event) => onChange(event.target.checked ? [...selected, form.id] : selected.filter((id) => id !== form.id))} className="h-4 w-4 rounded border-zinc-300 text-[#1E6BFF]" /><span><span className="block text-sm font-semibold">{form.name}</span><span className="text-xs text-[#64748B]">PDF espejo vinculado al expediente</span></span></label>)}</div>; }

function IdentityStep({ selected, onChange }: { selected: string[]; onChange: (value: string[]) => void }) { const options = ['Sin validación', 'OTP por correo', 'Identificación oficial', 'INE + selfie', 'CURP / RENAPO', 'RFC / SAT', 'e.firma SAT', 'Representante legal', 'Poder notarial', 'Validación bancaria']; return <div><div className="mb-4 flex flex-col gap-3 rounded-md border border-blue-100 bg-blue-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-blue-900">Políticas de identidad reutilizables</p><p className="mt-1 text-xs leading-5 text-blue-700">Versiona prueba de vida, documentación y decisiones desde el motor central.</p></div><Link href="/configuracion/verificacion-identidad" target="_blank" className="inline-flex h-9 flex-none items-center justify-center rounded-md border border-blue-200 bg-white px-3 text-xs font-semibold text-blue-700">Administrar políticas</Link></div><div className="grid gap-3 md:grid-cols-2">{options.map((option) => <label key={option} className={`flex cursor-pointer items-center gap-3 rounded-md border p-4 ${selected.includes(option) ? 'border-[#1E6BFF] bg-[#EFF6FF]' : 'border-[#E2E8F0] dark:border-border'}`}><input type="checkbox" checked={selected.includes(option)} onChange={(event) => onChange(event.target.checked ? option === 'Sin validación' ? [option] : [...selected.filter((item) => item !== 'Sin validación'), option] : selected.filter((item) => item !== option))} className="h-4 w-4 rounded border-zinc-300 text-[#1E6BFF]" /><span className="text-sm font-medium">{option}</span></label>)}</div></div>; }

function MilestonesStep({ milestones, onChange }: any) { return <div className="space-y-0">{milestones.map((item: any, index: number) => <div key={item.id} className="relative flex gap-4 pb-5 last:pb-0"><div className="flex flex-col items-center"><span className="flex h-8 w-8 items-center justify-center rounded-full border border-[#BFDBFE] bg-[#EFF6FF] text-xs font-semibold text-[#1E6BFF]">{index + 1}</span>{index < milestones.length - 1 && <span className="mt-1 w-px flex-1 bg-[#CBD5E1]" />}</div><div className="min-w-0 flex-1 rounded-md border border-[#E2E8F0] p-4 dark:border-border"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-[#64748B]">{item.description}</p></div><button onClick={() => onChange(milestones.filter((_: any, itemIndex: number) => itemIndex !== index))} className="text-[#94A3B8] hover:text-red-500"><Trash2 size={14} /></button></div><div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Responsable" value={item.responsible} onChange={(responsible) => onChange(milestones.map((current: any, currentIndex: number) => currentIndex === index ? { ...current, responsible } : current))} /><Field label="Condición de avance" value={item.condition} onChange={(condition) => onChange(milestones.map((current: any, currentIndex: number) => currentIndex === index ? { ...current, condition } : current))} /></div></div></div>)}</div>; }

function ClosureStep({ draft }: any) { return <div><div className="mb-5 rounded-md border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-start gap-3"><ShieldCheck size={19} className="mt-0.5 text-emerald-600" /><div><p className="text-sm font-semibold text-emerald-900">Cierre hermético</p><p className="mt-1 text-xs leading-5 text-emerald-800">Al cerrar se bloquearán documentos, formularios y firmas; se generarán el manifest, el hash raíz, el QR y la constancia.</p></div></div></div><div className="space-y-2">{draft.closureRules.map((rule: any) => <div key={rule.id} className="flex items-center gap-3 rounded-md border border-[#E2E8F0] px-4 py-3 dark:border-border"><span className="flex h-6 w-6 items-center justify-center rounded-full border border-[#CBD5E1] text-[#94A3B8]"><Check size={13} /></span><span className="flex-1 text-sm font-medium">{rule.label}</span><span className="text-xs text-[#64748B]">Se validará al cierre</span></div>)}</div><div className="mt-5 grid gap-3 md:grid-cols-3"><Summary label="Documentos" value={`${draft.requirements.filter((item: any) => item.required).length} obligatorios`} /><Summary label="Participantes" value={draft.participants.length} /><Summary label="Hitos" value={draft.milestones.length} /></div></div>; }

function Field({ label, value, onChange, placeholder = '', type = 'text' }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) { return <div><Label>{label}</Label><input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className={inputClass} /></div>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <div><Label>{label}</Label><select value={value} onChange={(event) => onChange(event.target.value)} className={inputClass}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>; }
function Label({ children }: { children: React.ReactNode }) { return <label className="mb-1.5 block text-xs font-medium text-[#475569] dark:text-muted-foreground">{children}</label>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-[#EFF6FF] px-2 py-0.5 text-[10px] font-semibold text-[#1E6BFF]">{children}</span>; }
function Summary({ label, value }: { label: string; value: React.ReactNode }) { return <div className="rounded-md bg-[#F6F8FB] p-3 dark:bg-background"><p className="text-[11px] uppercase text-[#94A3B8]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
const inputClass = 'h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10 dark:border-border dark:bg-background';
function formatToMime(format: string) { return ({ PDF: 'application/pdf', JPG: 'image/jpeg', PNG: 'image/png' } as Record<string, string>)[format] || format; }
