'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AlertTriangle, ArrowLeft, ArrowRight, Check, FileCheck2, FileUp, Loader2, Scale, ShieldCheck } from 'lucide-react';
import AppLayout from '@/components/AppLayout';
import { CertificationHeader, CertificationWorkspace, SandboxNotice } from '@/components/certifica/CertificationUI';
import { useWorkspace } from '@/contexts/WorkspaceContext';
import { useCertificaApi } from '@/lib/certifica/client';
import { CERTIFICATION_DECLARATION, CERTIFICATION_SERVICES, type CertificationServiceKey } from '@/lib/certifica/domain';

const steps = ['Documento', 'Analisis', 'Certificacion', 'Confirmacion', 'Resultado'];
type CaseRecord = { id: string; human_folio: string; status: string; original_filename?: string; original_sha256?: string; file_classification?: string; warnings?: string[]; service_key: CertificationServiceKey; provider_mode: string; total_amount?: number };

export default function NewCertificationPage() {
  const router = useRouter(); const { activeWorkspace } = useWorkspace(); const api = useCertificaApi();
  const [step, setStep] = useState(0); const [record, setRecord] = useState<CaseRecord | null>(null); const [title, setTitle] = useState(''); const [purpose, setPurpose] = useState('prove_integrity'); const [serviceKey, setServiceKey] = useState<CertificationServiceKey>('integrity'); const [providerMode, setProviderMode] = useState<'sandbox' | 'production'>('sandbox'); const [file, setFile] = useState<File | null>(null); const [accepted, setAccepted] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [publicUrl, setPublicUrl] = useState('');
  const progress = (step / 4) * 100;
  const service = CERTIFICATION_SERVICES[serviceKey];
  const canContinue = useMemo(() => step === 0 ? Boolean(title.trim().length >= 3 && file && activeWorkspace?.id) : step === 1 ? record?.status === 'ready' || record?.status === 'requires_review' : step === 2 ? true : step === 3 ? accepted : false, [accepted, activeWorkspace?.id, file, record?.status, step, title]);

  async function next() {
    if (!activeWorkspace?.id) return; setBusy(true); setError('');
    try {
      if (step === 0) {
        const created = await api<{ case: CaseRecord }>('/api/certifica/cases', { method: 'POST', body: JSON.stringify({ workspace_id: activeWorkspace.id, title, purpose_key: purpose, service_key: serviceKey, provider_mode: providerMode, idempotency_key: crypto.randomUUID() }) });
        const form = new FormData(); form.append('workspace_id', activeWorkspace.id); form.append('file', file!);
        const uploaded = await api<{ case: CaseRecord }>(`/api/certifica/cases/${created.case.id}/upload`, { method: 'POST', body: form }); setRecord(uploaded.case); setStep(1);
      } else if (step === 1) {
        const analyzed = await api<{ case: CaseRecord }>(`/api/certifica/cases/${record!.id}/analyze`, { method: 'POST', body: JSON.stringify({ workspace_id: activeWorkspace.id }) }); setRecord(analyzed.case); setStep(2);
      } else if (step === 2) {
        const updated = await api<{ case: CaseRecord }>(`/api/certifica/cases/${record!.id}`, { method: 'PATCH', body: JSON.stringify({ workspace_id: activeWorkspace.id, service_key: serviceKey, purpose_key: purpose }) }); setRecord(updated.case); setStep(3);
      } else if (step === 3) {
        const issued = await api<{ case: CaseRecord; public_url: string }>(`/api/certifica/cases/${record!.id}/submit`, { method: 'POST', body: JSON.stringify({ workspace_id: activeWorkspace.id, accept_declaration: true, idempotency_key: `${record!.id}:${serviceKey}:v1` }) }); setRecord(issued.case); setPublicUrl(issued.public_url); setStep(4);
      }
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo continuar.'); } finally { setBusy(false); }
  }
  return <AppLayout noPadding><CertificationWorkspace><CertificationHeader title="Nueva certificacion" description="Flujo guiado para preservar el original y emitir evidencia trazable." />
    <div className="mb-5 overflow-x-auto rounded-lg border border-slate-200 bg-white p-2"><div className="flex min-w-[680px] items-center">{steps.map((label, index) => <div key={label} className="flex flex-1 items-center"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-xs font-semibold ${index <= step ? 'bg-primary text-white' : 'bg-slate-100 text-slate-400'}`}>{index < step ? <Check size={15} /> : index + 1}</span><span className={`ml-2 text-xs font-semibold ${index <= step ? 'text-slate-900' : 'text-slate-400'}`}>{label}</span>{index < steps.length - 1 && <span className={`mx-3 h-px flex-1 ${index < step ? 'bg-primary' : 'bg-slate-200'}`} />}</div>)}</div></div>
    <div className="mb-5 flex items-center gap-3"><div className="h-1.5 flex-1 rounded-full bg-slate-200"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${progress}%` }} /></div><span className="text-xs font-semibold text-slate-500">{Math.round(progress)}%</span></div>
    {error && <div className="mb-4 flex items-start gap-2 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={16} className="mt-0.5" />{error}</div>}
    <section className="rounded-lg border border-slate-200 bg-white dark:border-border dark:bg-card">
      {step === 0 && <div className="grid gap-6 p-5 lg:grid-cols-[minmax(0,1fr)_360px]"><div><h2 className="text-lg font-semibold">Selecciona el documento</h2><p className="mt-1 text-sm text-slate-500">Se calculara el SHA-256 antes de almacenarlo. El original no se sobrescribe.</p><label className="mt-5 block text-sm font-semibold">Nombre de la operacion</label><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Ej. Contrato de suministro 2026" className="mt-2 h-10 w-full rounded-md border border-slate-200 px-3 text-sm outline-none focus:border-primary" /><label className="mt-4 block text-sm font-semibold">Finalidad</label><select value={purpose} onChange={(e) => setPurpose(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm"><option value="prove_integrity">Probar integridad</option><option value="prove_existence">Probar existencia en una fecha</option><option value="nom151_conservation">Conservar conforme a NOM-151</option><option value="validate_signatures">Validar firmas</option><option value="complete_evidence">Construir expediente probatorio</option></select></div><label className="flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed border-blue-300 bg-blue-50/40 p-6 text-center hover:bg-blue-50"><FileUp size={28} className="text-primary" /><span className="mt-3 text-sm font-semibold">{file?.name || 'Carga un PDF, imagen o XML'}</span><span className="mt-1 text-xs text-slate-500">Maximo 25 MB · almacenamiento privado</span><input type="file" accept=".pdf,.png,.jpg,.jpeg,.xml" className="sr-only" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label></div>}
      {step === 1 && <div className="p-5"><h2 className="text-lg font-semibold">Analisis previo</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><Info label="Original" value={record?.original_filename || 'Cargado'} /><Info label="Huella SHA-256" value={record?.original_sha256?.slice(0, 24) ? `${record.original_sha256.slice(0, 24)}...` : 'Calculada'} /><Info label="Seguridad" value="Listo para verificar" /></div><p className="mt-5 rounded-md bg-slate-50 p-3 text-sm text-slate-600">Al continuar se vuelve a calcular la huella, se inspecciona la estructura del PDF y se buscan firmas embebidas. La deteccion visual no se presenta como validacion criptografica.</p></div>}
      {step === 2 && <div className="p-5"><h2 className="text-lg font-semibold">Elige el alcance</h2><p className="mt-1 text-sm text-slate-500">Los productos PSC solo son legalmente validos cuando existe un proveedor productivo configurado.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{Object.entries(CERTIFICATION_SERVICES).map(([key, item]) => <button key={key} type="button" onClick={() => setServiceKey(key as CertificationServiceKey)} className={`min-h-36 rounded-lg border p-4 text-left transition ${serviceKey === key ? 'border-primary bg-blue-50 ring-2 ring-primary/10' : 'border-slate-200 hover:border-blue-200'}`}><div className="flex items-start justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-white text-primary"><ShieldCheck size={18} /></span><span className="text-sm font-semibold">{item.price ? `$${item.price} MXN` : 'Incluido'}</span></div><h3 className="mt-3 text-sm font-semibold">{item.name}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{item.description}</p></button>)}</div>{service.requiresPsc && <div className="mt-4"><SandboxNotice /><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={providerMode === 'production'} onChange={(e) => setProviderMode(e.target.checked ? 'production' : 'sandbox')} />Solicitar proveedor productivo configurado</label></div>}</div>}
      {step === 3 && <div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_340px]"><div><h2 className="text-lg font-semibold">Confirma la operacion</h2><dl className="mt-5 divide-y divide-slate-200 rounded-lg border border-slate-200"><Summary label="Documento" value={record?.original_filename || ''} /><Summary label="Servicio" value={service.name} /><Summary label="Proveedor" value={service.requiresPsc ? (providerMode === 'production' ? 'PSC productivo configurado' : 'Sandbox, sin validez PSC') : 'Docubox'} /><Summary label="Importe" value={service.price ? `$${service.price} MXN` : '$0 MXN'} /></dl><label className="mt-5 flex items-start gap-3 rounded-md border border-slate-200 p-4"><input type="checkbox" checked={accepted} onChange={(e) => setAccepted(e.target.checked)} className="mt-1" /><span><span className="block text-sm font-semibold">Declaracion del solicitante</span><span className="mt-1 block text-xs leading-5 text-slate-500">{CERTIFICATION_DECLARATION.text}</span></span></label></div><div className="rounded-lg border border-blue-100 bg-blue-50 p-5"><Scale className="text-primary" /><h3 className="mt-3 text-sm font-semibold">Alcance responsable</h3><p className="mt-2 text-xs leading-5 text-slate-600">Docubox acredita las huellas, eventos y evidencias que realmente fueron verificadas. No sustituye la funcion de un PSC cuando el producto la requiere.</p></div></div>}
      {step === 4 && <div className="flex min-h-[420px] flex-col items-center justify-center p-8 text-center"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><FileCheck2 size={30} /></span><h2 className="mt-5 text-2xl font-semibold">Operacion registrada</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">{record?.status === 'issued_with_warnings' ? 'La evidencia se emitio en sandbox y conserva la marca NO VALIDO / DEMOSTRACION.' : 'La integridad del original y el manifiesto quedaron registrados.'}</p><div className="mt-6 flex gap-2">{publicUrl && <button onClick={() => router.push(publicUrl)} className="h-9 rounded-md border border-slate-200 px-4 text-sm font-semibold">Verificar</button>}<button onClick={() => router.push(`/certificaciones/${record?.id}`)} className="h-9 rounded-md bg-primary px-4 text-sm font-semibold text-white">Abrir detalle</button></div></div>}
    </section>
    {step < 4 && <footer className="mt-4 flex items-center justify-between"><button type="button" onClick={() => step > 0 ? setStep(step - 1) : router.push('/certificaciones')} className="inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-3 text-sm font-semibold"><ArrowLeft size={15} />Atras</button><button type="button" disabled={!canContinue || busy} onClick={next} className="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{busy ? <Loader2 size={16} className="animate-spin" /> : null}{step === 3 ? 'Confirmar y emitir' : 'Continuar'}<ArrowRight size={15} /></button></footer>}
  </CertificationWorkspace></AppLayout>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-slate-200 p-4"><p className="text-xs font-semibold uppercase text-slate-400">{label}</p><p className="mt-2 break-all text-sm font-semibold">{value}</p></div>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 px-4 py-3"><dt className="text-sm text-slate-500">{label}</dt><dd className="text-right text-sm font-semibold">{value}</dd></div>; }

