'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { BadgeCheck, Check, FileText, KeyRound, Loader2, Send, ShieldCheck, X } from 'lucide-react';
import AppLogo from '@/components/ui/AppLogo';

type AccessData = { locked: boolean; recipientEmailHint?: string; subject?: string; folio?: string; notification?: { folio: string; subject: string; message: string; category: string; document: any; documentHash: string; dueAt?: string; allowedActions: string[] }; recipient?: { name: string; email: string } };

export default function NotificationRecipientPage() {
  const { token } = useParams<{ token: string }>();
  const [data, setData] = useState<AccessData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [responseText, setResponseText] = useState('');
  const [submitting, setSubmitting] = useState('');
  const [completed, setCompleted] = useState<{ label: string; hash: string } | null>(null);

  useEffect(() => { fetch(`/api/notificaciones/acceso/${encodeURIComponent(token)}`).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result.data); }).catch((caught) => setError(caught.message)).finally(() => setLoading(false)); }, [token]);
  const act = async (action: string) => { setSubmitting(action); setError(''); try { const response = await fetch(`/api/notificaciones/acceso/${encodeURIComponent(token)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, responseText }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setCompleted({ label: action === 'acknowledge' ? 'Acuse registrado' : action === 'accept' ? 'Aceptacion registrada' : action === 'reject' ? 'Rechazo registrado' : 'Respuesta registrada', hash: result.data.responseHash }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'No fue posible registrar la actuacion.'); } finally { setSubmitting(''); } };

  if (loading) return <div className="flex min-h-screen items-center justify-center bg-[#f6f8fb]"><Loader2 className="animate-spin text-primary" /></div>;
  return <div className="min-h-screen bg-[#f6f8fb] px-4 py-8 text-slate-950"><div className="mx-auto max-w-3xl"><header className="mb-6 flex items-center justify-between"><AppLogo className="w-[132px]" /><span className="inline-flex items-center gap-1.5 text-xs font-600 text-slate-500"><ShieldCheck size={14} className="text-emerald-600" />Acceso seguro</span></header>
    {error && !data ? <div className="rounded-lg border border-red-200 bg-white p-8 text-center"><X className="mx-auto text-red-500" /><h1 className="mt-3 text-lg font-600">No fue posible abrir la notificacion</h1><p className="mt-2 text-sm text-slate-500">{error}</p></div> : data?.locked ? <section className="rounded-lg border border-slate-200 bg-white p-7 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-blue-50 text-primary"><KeyRound size={24} /></span><h1 className="mt-5 text-xl font-600">Verificacion requerida</h1><p className="mt-2 text-sm leading-6 text-slate-500">Enviaremos un codigo de acceso a {data.recipientEmailHint}. La pantalla OTP se conectara al proveedor configurado para tu organizacion.</p><div className="mt-5 rounded-md bg-slate-50 px-4 py-3 text-left text-sm"><p className="font-600">{data.subject}</p><p className="mt-1 text-xs text-slate-500">{data.folio}</p></div></section> : completed ? <section className="rounded-lg border border-emerald-200 bg-white p-8 text-center"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Check size={28} /></span><h1 className="mt-5 text-2xl font-600">{completed.label}</h1><p className="mt-2 text-sm text-slate-500">Tu actuacion quedo vinculada al documento y a la cadena de evidencia.</p><p className="mt-5 break-all rounded-md bg-slate-50 p-3 font-mono text-[10px] text-slate-500">SHA-256 {completed.hash}</p></section> : data?.notification && <>
      <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-200 p-6"><div className="flex flex-wrap items-center gap-2 text-xs font-600 text-primary"><BadgeCheck size={15} />{data.notification.folio}<span className="text-slate-300">·</span><span className="text-slate-500">{data.notification.category}</span></div><h1 className="mt-3 text-2xl font-600">{data.notification.subject}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{data.notification.message || 'Se ha puesto un documento a tu disposicion para consulta y atencion.'}</p></div><div className="p-6"><div className="flex items-start gap-4 rounded-md border border-slate-200 p-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-md bg-cyan-50 text-cyan-700"><FileText size={20} /></span><div className="min-w-0"><p className="truncate text-sm font-600">{data.notification.document?.name || 'Documento notificado'}</p><p className="mt-1 text-xs text-slate-500">Version canonica registrada por Docubox</p><p className="mt-2 break-all font-mono text-[10px] text-slate-400">SHA-256 {data.notification.documentHash}</p></div></div></div></section>
      <section className="mt-4 rounded-lg border border-slate-200 bg-white p-6"><h2 className="text-sm font-600">Registra tu actuacion</h2>{data.notification.allowedActions.includes('respond') && <textarea value={responseText} onChange={(event) => setResponseText(event.target.value)} rows={4} placeholder="Escribe tu respuesta" className="mt-3 w-full rounded-md border border-slate-200 p-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/10" />}<div className="mt-4 flex flex-wrap justify-end gap-2">{data.notification.allowedActions.includes('reject') && <ActionButton action="reject" label="Rechazar" icon={X} submitting={submitting} onClick={act} secondary />}{data.notification.allowedActions.includes('respond') && <ActionButton action="respond" label="Enviar respuesta" icon={Send} submitting={submitting} onClick={act} />}{data.notification.allowedActions.includes('accept') && <ActionButton action="accept" label="Aceptar" icon={Check} submitting={submitting} onClick={act} />}{data.notification.allowedActions.includes('acknowledge') && <ActionButton action="acknowledge" label="Confirmar recepcion" icon={BadgeCheck} submitting={submitting} onClick={act} />}</div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}</section>
    </>}
  </div></div>;
}

function ActionButton({ action, label, icon: Icon, submitting, onClick, secondary = false }: { action: string; label: string; icon: React.ElementType; submitting: string; onClick: (action: string) => void; secondary?: boolean }) { return <button onClick={() => onClick(action)} disabled={Boolean(submitting)} className={`inline-flex h-10 items-center gap-2 rounded-md px-4 text-sm font-600 disabled:opacity-50 ${secondary ? 'border border-red-200 bg-white text-red-600' : 'bg-primary text-white'}`}>{submitting === action ? <Loader2 size={15} className="animate-spin" /> : <Icon size={15} />}{label}</button>; }
