-- Complete organization invitation lifecycle.
-- Tokens are generated by the backend and only their SHA-256 digest is stored.

ALTER TABLE public.organization_invitations
  ADD COLUMN IF NOT EXISTS token_prefix TEXT,
  ADD COLUMN IF NOT EXISTS delivery_status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS delivery_error_code TEXT,
  ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_sent_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS send_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS accepted_by UUID REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS revoked_by UUID REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS idempotency_key UUID,
  ADD COLUMN IF NOT EXISTS invitation_message TEXT;

ALTER TABLE public.organization_invitations
  DROP CONSTRAINT IF EXISTS organization_invitations_delivery_status_check;
ALTER TABLE public.organization_invitations
  ADD CONSTRAINT organization_invitations_delivery_status_check
  CHECK (delivery_status IN ('pending', 'sent', 'failed', 'skipped'));

ALTER TABLE public.organization_invitations
  DROP CONSTRAINT IF EXISTS organization_invitations_send_count_check;
ALTER TABLE public.organization_invitations
  ADD CONSTRAINT organization_invitations_send_count_check CHECK (send_count >= 0);

-- Keep the most recent pending invitation and close older duplicates before
-- installing the tenant-aware uniqueness rule.
WITH duplicates AS (
  SELECT id,
         row_number() OVER (
           PARTITION BY workspace_id, lower(btrim(email))
           ORDER BY created_at DESC, id DESC
         ) AS position
  FROM public.organization_invitations
  WHERE status = 'pending'
)
UPDATE public.organization_invitations invitation
SET status = 'revoked',
    revoked_at = COALESCE(invitation.revoked_at, CURRENT_TIMESTAMP),
    delivery_status = CASE WHEN invitation.delivery_status = 'pending' THEN 'skipped' ELSE invitation.delivery_status END
FROM duplicates
WHERE invitation.id = duplicates.id
  AND duplicates.position > 1;

CREATE UNIQUE INDEX IF NOT EXISTS uq_org_pending_invitation_email
  ON public.organization_invitations(workspace_id, lower(btrim(email)))
  WHERE status = 'pending';

CREATE UNIQUE INDEX IF NOT EXISTS uq_org_invitation_token_hash
  ON public.organization_invitations(token_hash)
  WHERE token_hash IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_org_invitation_idempotency
  ON public.organization_invitations(workspace_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_org_invitations_expiration
  ON public.organization_invitations(status, expires_at)
  WHERE status = 'pending';

-- Invitation mutations are backend-only. Authenticated clients may list the
-- operational metadata required by the organization screen, never token data.
REVOKE SELECT, INSERT, UPDATE, DELETE ON public.organization_invitations FROM authenticated;
GRANT SELECT (
  id, workspace_id, email, role_id, unit_id, status, delivery_status,
  delivery_error_code, sent_at, last_sent_at, send_count, expires_at,
  accepted_at, accepted_by, revoked_at, revoked_by, created_at
) ON public.organization_invitations TO authenticated;

CREATE OR REPLACE FUNCTION public.accept_organization_invitation(raw_token TEXT)
RETURNS TABLE (
  workspace_id UUID,
  workspace_name TEXT,
  membership_id UUID,
  membership_role public.workspace_member_role
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
  current_user_id UUID := auth.uid();
  current_email TEXT;
  invitation public.organization_invitations%ROWTYPE;
  selected_role public.organization_roles%ROWTYPE;
  resolved_membership public.workspace_members%ROWTYPE;
  resolved_workspace public.workspaces%ROWTYPE;
  digest_value TEXT;
  base_role public.workspace_member_role := 'member'::public.workspace_member_role;
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'organization_invitation_authentication_required';
  END IF;

  IF raw_token IS NULL OR length(raw_token) < 32 THEN
    RAISE EXCEPTION 'organization_invitation_invalid';
  END IF;

  SELECT lower(btrim(email)) INTO current_email
  FROM public.user_profiles
  WHERE id = current_user_id;

  IF current_email IS NULL THEN
    RAISE EXCEPTION 'organization_invitation_profile_missing';
  END IF;

  digest_value := encode(digest(raw_token, 'sha256'), 'hex');

  SELECT * INTO invitation
  FROM public.organization_invitations
  WHERE token_hash = digest_value
  FOR UPDATE;

  IF invitation.id IS NULL OR invitation.status <> 'pending' THEN
    RAISE EXCEPTION 'organization_invitation_invalid';
  END IF;

  IF invitation.expires_at <= CURRENT_TIMESTAMP THEN
    UPDATE public.organization_invitations
    SET status = 'expired'
    WHERE id = invitation.id;
    RAISE EXCEPTION 'organization_invitation_expired';
  END IF;

  IF lower(btrim(invitation.email)) <> current_email THEN
    RAISE EXCEPTION 'organization_invitation_email_mismatch';
  END IF;

  SELECT * INTO resolved_workspace
  FROM public.workspaces
  WHERE id = invitation.workspace_id
    AND organization_enabled = TRUE
  FOR UPDATE;

  IF resolved_workspace.id IS NULL THEN
    RAISE EXCEPTION 'organization_invitation_workspace_unavailable';
  END IF;

  IF invitation.role_id IS NOT NULL THEN
    SELECT * INTO selected_role
    FROM public.organization_roles
    WHERE id = invitation.role_id
      AND workspace_id = invitation.workspace_id;

    IF selected_role.id IS NULL OR selected_role.system_key = 'owner' THEN
      RAISE EXCEPTION 'organization_invitation_role_invalid';
    END IF;

    IF selected_role.system_key = 'admin' THEN
      base_role := 'admin'::public.workspace_member_role;
    END IF;
  END IF;

  INSERT INTO public.workspace_members (
    workspace_id, user_id, role, status, invited_by, joined_at
  ) VALUES (
    invitation.workspace_id, current_user_id, base_role, 'active', invitation.invited_by, CURRENT_TIMESTAMP
  )
  ON CONFLICT (workspace_id, user_id) DO UPDATE
  SET status = 'active',
      role = CASE
        WHEN public.workspace_members.role = 'owner'::public.workspace_member_role THEN public.workspace_members.role
        ELSE EXCLUDED.role
      END,
      invited_by = COALESCE(public.workspace_members.invited_by, EXCLUDED.invited_by),
      offboarded_at = NULL,
      suspended_at = NULL
  RETURNING * INTO resolved_membership;

  IF selected_role.id IS NOT NULL THEN
    INSERT INTO public.organization_member_roles (workspace_id, member_id, role_id, assigned_by)
    VALUES (invitation.workspace_id, resolved_membership.id, selected_role.id, invitation.invited_by)
    ON CONFLICT (member_id, role_id) DO NOTHING;
  END IF;

  IF invitation.unit_id IS NOT NULL THEN
    INSERT INTO public.organization_unit_members (unit_id, member_id)
    SELECT invitation.unit_id, resolved_membership.id
    WHERE EXISTS (
      SELECT 1 FROM public.organization_units unit
      WHERE unit.id = invitation.unit_id
        AND unit.workspace_id = invitation.workspace_id
        AND unit.status = 'active'
    )
    ON CONFLICT (unit_id, member_id) DO NOTHING;
  END IF;

  UPDATE public.organization_invitations
  SET status = 'accepted',
      accepted_at = CURRENT_TIMESTAMP,
      accepted_by = current_user_id,
      token_hash = NULL
  WHERE id = invitation.id;

  UPDATE public.organization_invitations
  SET status = 'revoked',
      revoked_at = CURRENT_TIMESTAMP,
      revoked_by = current_user_id,
      token_hash = NULL
  WHERE workspace_id = invitation.workspace_id
    AND lower(btrim(email)) = current_email
    AND status = 'pending'
    AND id <> invitation.id;

  INSERT INTO public.organization_audit_events (
    workspace_id, actor_user_id, event_type, resource_type, resource_id,
    summary, payload, outcome, severity, module, origin
  ) VALUES (
    invitation.workspace_id, current_user_id, 'member.invitation.accepted',
    'organization_invitation', invitation.id::TEXT,
    'Invitacion de organizacion aceptada',
    jsonb_build_object('membership_id', resolved_membership.id, 'email', current_email),
    'success', 'medium', 'members', 'public_link'
  );

  INSERT INTO public.notifications (user_id, type, title, description, priority, metadata)
  SELECT invitation.invited_by, 'organization', 'Invitacion aceptada',
         current_email || ' se unio a ' || resolved_workspace.name,
         'media', jsonb_build_object('workspace_id', invitation.workspace_id, 'member_id', resolved_membership.id)
  WHERE invitation.invited_by IS NOT NULL;

  RETURN QUERY SELECT resolved_workspace.id, resolved_workspace.name, resolved_membership.id, resolved_membership.role;
END;
$$;

REVOKE ALL ON FUNCTION public.accept_organization_invitation(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.accept_organization_invitation(TEXT) FROM anon;
GRANT EXECUTE ON FUNCTION public.accept_organization_invitation(TEXT) TO authenticated;

COMMENT ON FUNCTION public.accept_organization_invitation(TEXT) IS
  'Accepts a one-use organization invitation for the authenticated user after matching its email.';
